/* 生醫資訊研究技術 互動考題 — 題庫資料（中英雙語版）
 * Biomedical Informatics Research Techniques · Bilingual Question Bank.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"  · 多選 ans: ["A","C"]  · 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  biomedinfo: {
    label: "生醫資訊研究技術 互動考題",
    label_en: "BioMed Informatics Interactive Quiz",
    labels_en: {
      "核心研究流程": "Core Research Pipeline",
      "進階研究主題": "Advanced Topics",
      "Step 1：研究設計與假說": "Step 1: Research Design & Hypothesis",
      "Step 2：文獻檢索與系統性回顧": "Step 2: Literature Search & Systematic Review",
      "Step 3：公開資料庫探索": "Step 3: Public Database Mining",
      "Step 4：研究倫理與資料治理": "Step 4: Ethics & Data Governance",
      "Step 5：樣本量與統計檢定力": "Step 5: Sample Size & Power",
      "Step 6：統計假設檢定": "Step 6: Hypothesis Testing",
      "Step 7：多重檢定校正": "Step 7: Multiple Testing Correction",
      "Step 8：偏差、干擾與批次效應": "Step 8: Bias, Confounding & Batch Effects",
      "Step 9：存活分析": "Step 9: Survival Analysis",
      "Advanced：因果推論": "Advanced: Causal Inference",
      "Advanced：Meta 分析": "Advanced: Meta-analysis",
      "Advanced：可重現研究": "Advanced: Reproducible Research",
      "Advanced：數據視覺化": "Advanced: Data Visualization",
      "Advanced：科學寫作與發表": "Advanced: Scientific Writing & Publishing"
    },
    subjects: {
      "核心研究流程": {

        "Step 1：研究設計與假說": [
          { type:"single",
            stem:"PICO 框架中的「C」代表？",
            stem_en:"What does the 'C' in the PICO framework stand for?",
            A:"Condition（疾病狀態）", A_en:"Condition",
            B:"Comparison / Control（對照組）", B_en:"Comparison / Control",
            C:"Cohort（世代）", C_en:"Cohort",
            D:"Cost（成本）", D_en:"Cost",
            ans:"B",
            exp:"PICO = Population / Intervention / Comparison / Outcome。「C」是對照組，沒有對照組就無法談「差異」或「療效」。",
            exp_en:"PICO = Population / Intervention / Comparison / Outcome. 'C' is the comparator — without it there is no 'difference' or 'effect' to speak of." },
          { type:"single",
            stem:"以下哪個研究設計具有最強的因果推論能力？",
            stem_en:"Which study design provides the strongest causal inference?",
            A:"Case-control（病例對照）", A_en:"Case-control",
            B:"Cross-sectional（橫斷研究）", B_en:"Cross-sectional",
            C:"Randomized controlled trial（RCT）", C_en:"Randomized controlled trial (RCT)",
            D:"Case series（個案系列）", D_en:"Case series",
            ans:"C",
            exp:"RCT 透過隨機分配介入，能平衡已知與未知的干擾因子，是因果推論的金標準。",
            exp_en:"RCTs randomize the intervention, balancing both known and unknown confounders — the gold standard for causal inference." },
          { type:"single",
            stem:"想研究每 10 萬人僅 1 例的罕見疾病風險因子，最適合的觀察性設計？",
            stem_en:"For a rare disease (~1 per 100,000), which observational design is most efficient?",
            A:"Prospective cohort（前瞻世代）", A_en:"Prospective cohort",
            B:"Case-control（病例對照）", B_en:"Case-control",
            C:"Cross-sectional（橫斷研究）", C_en:"Cross-sectional",
            D:"Ecological study（生態研究）", D_en:"Ecological study",
            ans:"B",
            exp:"罕見疾病用 cohort 追蹤需巨量樣本與長期觀察，case-control 可從少量已知病例反查暴露，效率高很多。",
            exp_en:"Cohorts need massive samples for rare diseases. Case-control starts from existing cases and looks back for exposures — far more efficient." },
          { type:"single",
            stem:"關於 HARKing（事後造假說）的主要危害是？",
            stem_en:"What is the principal harm of HARKing (Hypothesizing After the Results are Known)?",
            A:"資料量過大", A_en:"Excessive data volume",
            B:"第一型錯誤膨脹、研究難以重現", B_en:"Inflated Type I error and irreproducibility",
            C:"違反 GDPR", C_en:"Violates GDPR",
            D:"樣本量不足", D_en:"Insufficient sample size",
            ans:"B",
            exp:"看完結果再「補上」假說，會把巧合關聯當成「發現」，導致 false positive 暴增、後續研究無法重現。",
            exp_en:"Fitting hypotheses after seeing results turns coincidences into 'findings,' inflating false positives and ruining reproducibility." },
          { type:"multi",
            stem:"FINER 準則中的五個項目包含哪些？（多選）",
            stem_en:"Which items are part of the FINER criteria? (Multiple)",
            A:"Feasible（可行）", A_en:"Feasible",
            B:"Interesting（有趣）", B_en:"Interesting",
            C:"Novel（新穎）", C_en:"Novel",
            D:"Numeric（數值化）", D_en:"Numeric",
            ans:["A","B","C"],
            exp:"FINER = Feasible / Interesting / Novel / Ethical / Relevant。Numeric 不在內。",
            exp_en:"FINER = Feasible / Interesting / Novel / Ethical / Relevant. Numeric is NOT part of it." },
          { type:"tf",
            stem:"是非題：橫斷研究 (cross-sectional) 可以明確判斷暴露與疾病的因果方向。",
            stem_en:"True/False: A cross-sectional study can determine the causal direction between exposure and disease.",
            ans:"F",
            exp:"橫斷研究只在「單一時間點」同時測量暴露與結果，無法判斷哪個先發生，因此無法確認因果方向。",
            exp_en:"Cross-sectional studies measure exposure and outcome at the same time point — they cannot establish which came first or causal direction." },
          { type:"single",
            stem:"研究發表前，將假說、終點與分析計畫公開註冊的主要目的為何？",
            stem_en:"What is the main purpose of pre-registering hypotheses, endpoints, and analysis plans?",
            A:"加快期刊接受", A_en:"Speed up journal acceptance",
            B:"避免 p-hacking 與 HARKing，提升可信度", B_en:"Avoid p-hacking and HARKing, boost credibility",
            C:"提高 impact factor", C_en:"Boost impact factor",
            D:"符合 GDPR", D_en:"Comply with GDPR",
            ans:"B",
            exp:"預先註冊（OSF、ClinicalTrials.gov）把研究從「探索性」拉升到「確證性」，事後挑數據與造假說都會留下證據。",
            exp_en:"Pre-registration (OSF, ClinicalTrials.gov) elevates a study from exploratory to confirmatory, leaving a clear record of any post-hoc deviation." },
          { type:"single",
            stem:"使用 TCGA 公開資料做「次級分析」時，最重要的研究設計考量為何？",
            stem_en:"When using TCGA public data for secondary analysis, the most important design consideration is:",
            A:"資料量很大不需考量", A_en:"Sample size is large enough to skip checks",
            B:"原始 cohort 的納入排除標準與批次結構", B_en:"The original cohort's inclusion/exclusion criteria and batch structure",
            C:"使用的繪圖軟體版本", C_en:"The plotting software version",
            D:"作者所屬機構", D_en:"The authors' institution",
            ans:"B",
            exp:"TCGA 樣本多為手術切除標本（偏向早期可切除），且來自多個 sequencing center；忽略此事會嚴重影響可推論性。",
            exp_en:"TCGA samples mostly come from surgical resections (early, resectable tumors) and multiple sequencing centers; ignoring this severely limits generalizability." },
          { type:"single",
            stem:"研究設計中所謂的「primary endpoint」應如何決定？",
            stem_en:"How should the primary endpoint be decided in a study design?",
            A:"資料分析後挑最顯著的指標", A_en:"Pick the most significant metric after analysis",
            B:"研究開始前事先指定", B_en:"Pre-specify before the study starts",
            C:"投稿時依期刊喜好調整", C_en:"Adjust according to journal preferences at submission",
            D:"看 reviewer 意見後修改", D_en:"Modify after reviewer comments",
            ans:"B",
            exp:"primary endpoint 必須事前指定（preferably 預先註冊），事後挑指標等同於 p-hacking。",
            exp_en:"The primary endpoint must be pre-specified (ideally pre-registered); post-hoc selection is p-hacking." },
          { type:"single",
            stem:"研究問題「在 18-65 歲第二型糖尿病患者中，metformin 相較於 sulfonylurea，5 年內全因死亡率為何？」屬於哪種框架？",
            stem_en:"The question 'In T2DM patients aged 18-65, how does metformin vs sulfonylurea affect 5-year all-cause mortality?' uses which framework?",
            A:"PICO", A_en:"PICO",
            B:"PICOT", B_en:"PICOT",
            C:"FINER", C_en:"FINER",
            D:"CONSORT", D_en:"CONSORT",
            ans:"B",
            exp:"明確包含 Population + Intervention + Comparison + Outcome + Timeframe（5 年）→ PICOT。",
            exp_en:"It explicitly includes Population + Intervention + Comparison + Outcome + Timeframe (5 years) → PICOT." }
        ],

        "Step 2：文獻檢索與系統性回顧": [
          { type:"single",
            stem:"PubMed 的 MeSH 主要解決哪一個檢索問題？",
            stem_en:"What problem does PubMed's MeSH primarily solve?",
            A:"加快下載速度", A_en:"Speeds up download",
            B:"同義詞無法窮舉的問題（如 'heart attack' 與 'myocardial infarction'）", B_en:"Exhaustive synonym coverage (e.g., 'heart attack' vs 'myocardial infarction')",
            C:"自動翻譯成中文", C_en:"Auto-translate to Chinese",
            D:"自動產生圖表", D_en:"Auto-generate plots",
            ans:"B",
            exp:"MeSH 是 NLM 維護的層級式醫學詞彙，搜尋一個 MeSH 詞會自動展開所有同義詞與下位詞，確保不漏文章。",
            exp_en:"MeSH is NLM's hierarchical medical thesaurus — searching a MeSH term auto-expands to all synonyms and narrower terms." },
          { type:"single",
            stem:"PubMed 檢索式 `\"asthma\"[tiab]` 是在搜尋哪個欄位？",
            stem_en:"What does the PubMed tag `\"asthma\"[tiab]` search?",
            A:"作者所屬機構", A_en:"Author affiliation",
            B:"標題與摘要", B_en:"Title AND abstract",
            C:"期刊全名", C_en:"Journal title",
            D:"出版年份", D_en:"Publication year",
            ans:"B",
            exp:"[tiab] = title + abstract，是 PubMed 常用欄位標記，可同時在標題與摘要中找關鍵字。",
            exp_en:"[tiab] = title + abstract, a common PubMed tag for searching both fields simultaneously." },
          { type:"single",
            stem:"在系統性回顧的 PubMed 檢索式中，同義詞之間應使用哪個布林運算符連結？",
            stem_en:"In a systematic review's PubMed query, which Boolean operator connects synonyms?",
            A:"AND", A_en:"AND",
            B:"OR", B_en:"OR",
            C:"NOT", C_en:"NOT",
            D:"XOR", D_en:"XOR",
            ans:"B",
            exp:"OR 取聯集，連結同義詞（如 tumor OR neoplasm OR cancer）；AND 用於概念群之間（如「腫瘤」AND「治療」AND「存活」）。",
            exp_en:"OR unions synonyms (e.g., tumor OR neoplasm OR cancer); AND combines different concept groups." },
          { type:"single",
            stem:"PRISMA 流程圖必須呈現的四個階段順序為？",
            stem_en:"What is the order of the four stages in a PRISMA flow diagram?",
            A:"Screening → Identification → Eligibility → Included", A_en:"Screening → Identification → Eligibility → Included",
            B:"Identification → Screening → Eligibility → Included", B_en:"Identification → Screening → Eligibility → Included",
            C:"Identification → Eligibility → Screening → Included", C_en:"Identification → Eligibility → Screening → Included",
            D:"Included → Identification → Screening → Eligibility", D_en:"Included → Identification → Screening → Eligibility",
            ans:"B",
            exp:"PRISMA 是漏斗式縮小：Identification（初始檢出）→ Screening（去重+標題篩選）→ Eligibility（全文評估）→ Included（最終納入）。",
            exp_en:"PRISMA is a funnel: Identification → Screening (dedup + title/abstract) → Eligibility (full-text) → Included." },
          { type:"multi",
            stem:"系統性回顧建議至少檢索哪些資料庫？（多選）",
            stem_en:"A systematic review should search at least which databases? (Multiple)",
            A:"PubMed / MEDLINE", A_en:"PubMed / MEDLINE",
            B:"Embase", B_en:"Embase",
            C:"Cochrane Library", C_en:"Cochrane Library",
            D:"Wikipedia", D_en:"Wikipedia",
            ans:["A","B","C"],
            exp:"PRISMA 與 Cochrane 都建議至少 PubMed + Embase + Cochrane，因每個資料庫收錄期刊不同。Wikipedia 不是學術資料庫。",
            exp_en:"PRISMA and Cochrane both recommend at least PubMed + Embase + Cochrane (different journal coverage). Wikipedia is not an academic database." },
          { type:"tf",
            stem:"是非題：在系統性回顧中，使用 NOT 排除特定文獻是安全的做法，因為能精準篩除無關研究。",
            stem_en:"True/False: Using NOT to exclude papers is safe in systematic reviews because it precisely removes irrelevant studies.",
            ans:"F",
            exp:"NOT 容易誤刪相關文章（例如同篇兼論兩主題），系統性回顧檢索應謹慎使用，並記錄影響。",
            exp_en:"NOT can accidentally drop relevant papers (e.g., articles covering two topics). Use sparingly in SRs and document its impact." },
          { type:"single",
            stem:"以下哪個工具是雙人盲審「文獻篩選 (screening)」階段的常用平台？",
            stem_en:"Which tool is commonly used for blinded dual-screening of references?",
            A:"GraphPad Prism", A_en:"GraphPad Prism",
            B:"Rayyan / Covidence", B_en:"Rayyan / Covidence",
            C:"PyMOL", C_en:"PyMOL",
            D:"Cytoscape", D_en:"Cytoscape",
            ans:"B",
            exp:"Rayyan 與 Covidence 提供雙人盲審介面、衝突解決機制與 PRISMA 流程圖匯出。",
            exp_en:"Rayyan and Covidence offer blinded dual-screening, conflict resolution, and PRISMA flow exports." },
          { type:"single",
            stem:"PubMed 欄位標記 `[dp]` 用來限制？",
            stem_en:"The PubMed field tag `[dp]` is used to limit:",
            A:"作者", A_en:"Author",
            B:"出版日期", B_en:"Publication date",
            C:"研究類型", C_en:"Publication type",
            D:"國家", D_en:"Country",
            ans:"B",
            exp:"[dp] = date of publication，用於限制出版年份範圍，如 `\"2015\"[dp]:\"2026\"[dp]`。",
            exp_en:"[dp] = date of publication, used for date ranges like `\"2015\"[dp]:\"2026\"[dp]`." },
          { type:"single",
            stem:"以下哪個是預印本（preprint）伺服器，而非經過同儕審查的資料庫？",
            stem_en:"Which is a preprint server, NOT a peer-reviewed database?",
            A:"PubMed", A_en:"PubMed",
            B:"medRxiv", B_en:"medRxiv",
            C:"Cochrane Library", C_en:"Cochrane Library",
            D:"Web of Science", D_en:"Web of Science",
            ans:"B",
            exp:"medRxiv 與 bioRxiv 為未經同儕審查的預印本伺服器；其他三者皆為同儕審查內容索引。",
            exp_en:"medRxiv and bioRxiv host non-peer-reviewed preprints; the others index peer-reviewed content." },
          { type:"multi",
            stem:"執行系統性回顧檢索時，應記錄哪些資訊以確保可重現？（多選）",
            stem_en:"To ensure reproducibility, what should you record for a SR search? (Multiple)",
            A:"完整檢索式（逐字）", A_en:"Verbatim full search query",
            B:"檢索日期", B_en:"Date of the search",
            C:"檢索的資料庫名稱與版本", C_en:"Database names and versions",
            D:"使用的電腦廠牌", D_en:"Computer brand used",
            ans:["A","B","C"],
            exp:"檢索式、日期、資料庫是可重現的必備項目；硬體無關。",
            exp_en:"Query, date, and database are essential for reproducibility; hardware is irrelevant." }
        ],

        "Step 3：公開資料庫探索": [
          { type:"single",
            stem:"GRCh37 (hg19) 與 GRCh38 的座標關係為何？",
            stem_en:"What is the relationship between GRCh37 (hg19) and GRCh38 coordinates?",
            A:"完全相同，可直接互通", A_en:"Identical and directly interchangeable",
            B:"差別很小，誤差可忽略", B_en:"Differences are negligible",
            C:"許多區段重新排列，必須用 liftOver/CrossMap 轉換", C_en:"Many regions are rearranged — must convert with liftOver/CrossMap",
            D:"只有 X 染色體不同", D_en:"Only the X chromosome differs",
            ans:"C",
            exp:"GRCh37 與 GRCh38 在許多區段重新排列、修正錯誤，座標不能直接互通。混用會讓 BED/VCF 落在錯誤位置。",
            exp_en:"GRCh37 and GRCh38 reorganize many regions; coordinates do NOT match. Mixing silently corrupts BED/VCF data." },
          { type:"single",
            stem:"想做泛癌 (33 癌種) 多體學分析，首選資料庫為？",
            stem_en:"First-choice database for pan-cancer (33 cancer types) multi-omics analysis?",
            A:"GEO", A_en:"GEO",
            B:"TCGA", B_en:"TCGA",
            C:"GTEx", C_en:"GTEx",
            D:"MIMIC-IV", D_en:"MIMIC-IV",
            ans:"B",
            exp:"TCGA 收錄 33 種癌症的 RNA-seq、WES、WGS、甲基化、蛋白表達與臨床資料，是泛癌標準集合。",
            exp_en:"TCGA covers 33 cancers with RNA-seq, WES, WGS, methylation, protein, and clinical data — the pan-cancer standard." },
          { type:"single",
            stem:"關於 UK Biobank 的存取規定，下列何者正確？",
            stem_en:"Which is correct about UK Biobank access?",
            A:"完全免費下載", A_en:"Completely free download",
            B:"需提交研究計畫申請並付平台費", B_en:"Application + platform fee required",
            C:"僅開放給英國公民", C_en:"UK citizens only",
            D:"任何人都能取得個案層級的姓名", D_en:"Anyone can obtain individual-level names",
            ans:"B",
            exp:"UK Biobank 採「open access for bona fide researchers」原則：提交研究計畫經審查後付費取得，全球研究者皆可申請。",
            exp_en:"UK Biobank uses an 'open access for bona fide researchers' model — proposal review + fee, open to global researchers." },
          { type:"single",
            stem:"健康組織的基因表達參考資料庫（54 個組織）通常是？",
            stem_en:"Which database provides RNA-seq from 54 healthy human tissues as a reference?",
            A:"TCGA", A_en:"TCGA",
            B:"GTEx", B_en:"GTEx",
            C:"MIMIC", C_en:"MIMIC",
            D:"ClinVar", D_en:"ClinVar",
            ans:"B",
            exp:"GTEx (Genotype-Tissue Expression) 提供約 1,000 位捐贈者、54 個健康組織的 RNA-seq，是癌症與疾病研究的「正常組織」對照標準。",
            exp_en:"GTEx provides RNA-seq from ~1,000 donors across 54 healthy tissues — the standard 'normal tissue' reference for disease studies." },
          { type:"multi",
            stem:"以下哪些是「需要申請才能取得個案層級資料」的資料庫？（多選）",
            stem_en:"Which databases require formal application for individual-level access? (Multiple)",
            A:"UK Biobank", A_en:"UK Biobank",
            B:"MIMIC-IV", B_en:"MIMIC-IV",
            C:"dbGaP (TCGA germline)", C_en:"dbGaP (TCGA germline)",
            D:"GEO 公開資料", D_en:"Public GEO data",
            ans:["A","B","C"],
            exp:"UK Biobank、MIMIC-IV (PhysioNet credential)、dbGaP（含 TCGA germline VCF）皆為受控存取。GEO 公開資料無需申請。",
            exp_en:"UK Biobank, MIMIC-IV (PhysioNet credential), and dbGaP are controlled-access. Public GEO data is open." },
          { type:"tf",
            stem:"是非題：Excel 開啟 RNA-seq 表達表時，會把 SEPT2、MARCH1 自動轉成日期，這是知名的資料污染。",
            stem_en:"True/False: Excel auto-converts gene symbols like SEPT2, MARCH1 to dates — a notorious data corruption issue.",
            ans:"T",
            exp:"Excel 把基因名稱誤判為日期是 20+ 年的問題；HGNC 於 2020 重新命名這些基因（如 SEPT2 → SEPTIN2）。處理前以 biomaRt / mygene 等工具程式化轉換並鎖版本最安全。",
            exp_en:"Excel's date-auto-conversion has plagued genomics for 20+ years; HGNC renamed affected genes in 2020 (e.g., SEPT2 → SEPTIN2). Use biomaRt / mygene programmatically." },
          { type:"single",
            stem:"以下哪個資料庫主要儲存「臨床顯著的基因變異」與其臨床意義？",
            stem_en:"Which database stores 'clinically significant' genetic variants with interpretation?",
            A:"ClinVar", A_en:"ClinVar",
            B:"GEO", B_en:"GEO",
            C:"GTEx", C_en:"GTEx",
            D:"PRIDE", D_en:"PRIDE",
            ans:"A",
            exp:"ClinVar 由 NCBI 維護，整合各國實驗室提交的臨床相關變異，給予 Pathogenic / Benign / VUS 評級。",
            exp_en:"ClinVar (NCBI) aggregates clinically relevant variants from labs worldwide with Pathogenic / Benign / VUS interpretations." },
          { type:"single",
            stem:"想查詢「歐裔人群某 SNP 的群體頻率」，最權威的資料庫為？",
            stem_en:"For population allele frequency of a SNP in Europeans, the authoritative database is:",
            A:"gnomAD", A_en:"gnomAD",
            B:"PubMed", B_en:"PubMed",
            C:"TCGA", C_en:"TCGA",
            D:"UCSC", D_en:"UCSC",
            ans:"A",
            exp:"gnomAD（v4 含超過 80 萬樣本）提供按族群分層的 SNV/indel 頻率，是變異註釋與罕病解讀的標準。",
            exp_en:"gnomAD (v4, 800k+ samples) provides population-stratified SNV/indel frequencies — the standard for variant annotation and rare-disease interpretation." },
          { type:"single",
            stem:"在合併多個 GEO RNA-seq 資料集前，為何要處理「批次效應」？",
            stem_en:"Why correct batch effects before merging multiple GEO RNA-seq datasets?",
            A:"節省硬碟空間", A_en:"Save disk space",
            B:"避免技術變異被誤當作生物學差異", B_en:"Avoid technical variation being mistaken for biology",
            C:"符合 GEO 政策", C_en:"Required by GEO policy",
            D:"加速 PCA 運算", D_en:"Speed up PCA",
            ans:"B",
            exp:"不同實驗室、平台、年代會產生系統性偏差；未校正會讓 PCA / clustering 被批次主導，得出錯誤生物學結論。",
            exp_en:"Different labs / platforms / years create systematic shifts; uncorrected, PCA and clustering are dominated by batch — yielding false biology." },
          { type:"single",
            stem:"使用 R 套件 `TCGAbiolinks` 主要可以做什麼？",
            stem_en:"What is the R package `TCGAbiolinks` mainly used for?",
            A:"建立 TCGA 帳號", A_en:"Create a TCGA account",
            B:"查詢、下載與整理 TCGA 多體學與臨床資料", B_en:"Query, download, and curate TCGA multi-omics + clinical data",
            C:"執行 BLAST", C_en:"Run BLAST",
            D:"撰寫論文", D_en:"Write manuscripts",
            ans:"B",
            exp:"TCGAbiolinks 透過 GDC API 直接抓取 TCGA 各種資料類型、自動處理 manifest、回傳已整理的 SummarizedExperiment 物件。",
            exp_en:"TCGAbiolinks queries the GDC API for TCGA data, handles manifests, and returns ready-to-use SummarizedExperiment objects." }
        ],

        "Step 4：研究倫理與資料治理": [
          { type:"single",
            stem:"《貝爾蒙報告》(Belmont Report) 提出的三大倫理原則是？",
            stem_en:"What are the three principles in the Belmont Report?",
            A:"Respect for Persons / Beneficence / Justice", A_en:"Respect for Persons / Beneficence / Justice",
            B:"Honesty / Reliability / Punctuality", B_en:"Honesty / Reliability / Punctuality",
            C:"Profit / Speed / Accuracy", C_en:"Profit / Speed / Accuracy",
            D:"FAIR / Open / Free", D_en:"FAIR / Open / Free",
            ans:"A",
            exp:"1979 年貝爾蒙報告奠定了當代人體研究倫理三原則：尊重人格、有利原則、正義原則。",
            exp_en:"The 1979 Belmont Report established three principles of modern human-subjects research: Respect for Persons, Beneficence, Justice." },
          { type:"single",
            stem:"HIPAA Safe Harbor 規定要移除多少項識別資訊才能視為「去識別化」？",
            stem_en:"How many identifiers must HIPAA Safe Harbor remove to qualify as 'de-identified'?",
            A:"10", A_en:"10",
            B:"12", B_en:"12",
            C:"18", C_en:"18",
            D:"25", D_en:"25",
            ans:"C",
            exp:"HIPAA Safe Harbor 列出 18 項必須移除的識別資訊，從姓名、地址、日期到 IP、URL、生物識別。",
            exp_en:"HIPAA Safe Harbor specifies 18 identifiers to remove — from names, addresses, dates to IPs, URLs, and biometrics." },
          { type:"single",
            stem:"處理歐盟居民健康資料應遵循哪項法規？",
            stem_en:"Which regulation governs the processing of EU residents' health data?",
            A:"HIPAA", A_en:"HIPAA",
            B:"GDPR", B_en:"GDPR",
            C:"FAIR", C_en:"FAIR",
            D:"CITI", D_en:"CITI",
            ans:"B",
            exp:"歐盟通用資料保護法 (GDPR, 2016/679) 對歐盟居民的個資處理有最嚴格的規範，含明確同意、被遺忘權、跨境傳輸限制。",
            exp_en:"The EU's General Data Protection Regulation (2016/679) imposes the strictest rules for processing EU residents' data, including explicit consent and right to erasure." },
          { type:"single",
            stem:"FAIR 資料原則中的「I」代表？",
            stem_en:"What does the 'I' in the FAIR principles stand for?",
            A:"Independent", A_en:"Independent",
            B:"Identifiable", B_en:"Identifiable",
            C:"Interoperable", C_en:"Interoperable",
            D:"Indexable", D_en:"Indexable",
            ans:"C",
            exp:"FAIR = Findable / Accessible / Interoperable / Reusable，是 NIH/EU 資料管理計畫的標準。",
            exp_en:"FAIR = Findable / Accessible / Interoperable / Reusable — the standard for NIH/EU data management plans." },
          { type:"multi",
            stem:"以下哪些屬於 HIPAA Safe Harbor 列出的 18 項識別資訊？（多選）",
            stem_en:"Which of these are among HIPAA Safe Harbor's 18 identifiers? (Multiple)",
            A:"姓名", A_en:"Names",
            B:"完整出生日期", B_en:"Full dates of birth",
            C:"病歷號", C_en:"Medical record numbers",
            D:"研究主題", D_en:"Research topic",
            ans:["A","B","C"],
            exp:"姓名、日期、病歷號都列入 18 項；研究主題不屬識別資訊。",
            exp_en:"Names, dates, and MRNs are all in the 18-item list. Research topic is not an identifier." },
          { type:"tf",
            stem:"是非題：完全去名 (de-identified) 的基因組資料絕對無法被再識別。",
            stem_en:"True/False: De-identified genomic data can absolutely never be re-identified.",
            ans:"F",
            exp:"Gymrek et al. (Science 2013) 顯示，去名後的 Y 染色體 SNP 與公開姓氏資料庫結合，可反查到本人。基因組資料的再識別風險不可忽視。",
            exp_en:"Gymrek et al. (Science 2013) demonstrated re-identification of de-identified Y-chromosome data via public surname databases. Genomic re-identification is a real risk." },
          { type:"single",
            stem:"Obermeyer et al. (Science 2019) 揭露美國某健康風險預測演算法的偏倚，問題出在？",
            stem_en:"Obermeyer et al. (Science 2019) exposed bias in a US health-risk algorithm. The root cause was:",
            A:"資料外洩", A_en:"Data breach",
            B:"用『醫療支出』當作健康狀態 proxy，低估黑人病患風險", B_en:"Using healthcare cost as a proxy for need, underestimating Black patients' risk",
            C:"模型過擬合", C_en:"Model overfitting",
            D:"訓練樣本太少", D_en:"Insufficient training samples",
            ans:"B",
            exp:"演算法用「醫療支出」當健康風險指標。因結構性醫療使用差異，黑人病患同樣健康狀態下花費較少，導致他們被系統性低估風險、分配較少資源。",
            exp_en:"The algorithm used healthcare spending as a health proxy. Due to structural usage differences, Black patients with equivalent illness incurred lower costs — systematically lowering their predicted risk." },
          { type:"single",
            stem:"在台灣，所有涉及人體受試者的研究須通過？",
            stem_en:"In Taiwan, all human-subjects research must be reviewed by:",
            A:"國家通訊傳播委員會", A_en:"National Communications Commission",
            B:"IRB / REC（人體研究倫理委員會）", B_en:"IRB / REC (Research Ethics Committee)",
            C:"金管會", C_en:"Financial Supervisory Commission",
            D:"教育部", D_en:"Ministry of Education",
            ans:"B",
            exp:"台灣《人體研究法》要求所有人體研究需通過 REC/IRB 審查並取得知情同意。",
            exp_en:"Taiwan's Human Subjects Research Act requires REC/IRB review and informed consent for all human-subjects research." },
          { type:"single",
            stem:"關於 PRS (polygenic risk score) 跨族群應用的主要倫理疑慮為？",
            stem_en:"What is the main ethical concern with cross-population use of polygenic risk scores (PRS)?",
            A:"計算成本太高", A_en:"Too computationally expensive",
            B:"GWAS 訓練樣本以歐裔為主，PRS 在非歐裔表現顯著下降，加劇健康不平等", B_en:"GWAS training data are mostly European; PRS performance drops in non-Europeans, worsening disparities",
            C:"違反 HIPAA", C_en:"Violates HIPAA",
            D:"GWAS 資料無法公開", D_en:"GWAS data cannot be made public",
            ans:"B",
            exp:"~80% GWAS 樣本為歐裔；PRS 用於非歐裔時 AUC 大幅下降。多元 cohort（H3Africa、PAGE、All of Us）正在解決此問題。",
            exp_en:"~80% of GWAS samples are European; PRS AUC drops in non-European groups. Initiatives like H3Africa, PAGE, and All of Us aim to fix this." },
          { type:"single",
            stem:"涉及動物實驗的研究需經哪個委員會審查？",
            stem_en:"Animal research must be approved by which committee?",
            A:"IRB（人體）", A_en:"IRB (human)",
            B:"IACUC（動物照護與使用委員會）", B_en:"IACUC (Institutional Animal Care and Use Committee)",
            C:"DSMB", C_en:"DSMB",
            D:"NIH", D_en:"NIH",
            ans:"B",
            exp:"動物實驗由 IACUC 審查，應用 3R 原則（Replace / Reduce / Refine）並符合 ARRIVE 報告指引。",
            exp_en:"Animal research is reviewed by IACUC, following the 3Rs (Replace / Reduce / Refine) and ARRIVE reporting guidelines." }
        ],

        "Step 5：樣本量與統計檢定力": [
          { type:"single",
            stem:"統計檢定中，α 通常代表？",
            stem_en:"In hypothesis testing, α typically represents:",
            A:"第一型錯誤率", A_en:"Type I error rate",
            B:"第二型錯誤率", B_en:"Type II error rate",
            C:"效應量", C_en:"Effect size",
            D:"樣本量", D_en:"Sample size",
            ans:"A",
            exp:"α = P(拒絕 H₀ | H₀ 為真) = 第一型錯誤率；β = 第二型錯誤率，1-β = 檢定力。",
            exp_en:"α = P(reject H₀ | H₀ true) = Type I error rate; β = Type II error rate, 1-β = power." },
          { type:"single",
            stem:"當 Cohen's d 由 0.5 減為 0.25，所需樣本量約變為？",
            stem_en:"If Cohen's d drops from 0.5 to 0.25, required sample size becomes approximately:",
            A:"2 倍", A_en:"2x",
            B:"4 倍", B_en:"4x",
            C:"8 倍", C_en:"8x",
            D:"不變", D_en:"Unchanged",
            ans:"B",
            exp:"樣本量公式 n ∝ 1/Δ²；效應量減半 → 樣本量約 4 倍。",
            exp_en:"Sample size scales as 1/Δ². Halving the effect quadruples the required sample." },
          { type:"single",
            stem:"GWAS 為什麼用 α = 5×10⁻⁸ 作為顯著閾值？",
            stem_en:"Why does GWAS use α = 5×10⁻⁸?",
            A:"NIH 規定", A_en:"NIH regulation",
            B:"約等於 0.05 / 10⁶（百萬個獨立 LD block 的 Bonferroni）", B_en:"Approximately 0.05 / 10⁶ — Bonferroni for ~1M independent LD blocks",
            C:"Cohen 建議", C_en:"Cohen's recommendation",
            D:"國際標準會議", D_en:"International standards body",
            ans:"B",
            exp:"人類基因組約 10⁶ 個獨立 LD block；0.05 / 10⁶ = 5×10⁻⁸ 即基因組尺度 Bonferroni 閾值。",
            exp_en:"The human genome has ~10⁶ independent LD blocks; 0.05/10⁶ = 5×10⁻⁸ — a genome-wide Bonferroni threshold." },
          { type:"single",
            stem:"關於「事後檢定力 (post-hoc power)」，下列何者正確？",
            stem_en:"Which statement about post-hoc power is correct?",
            A:"可用以證明「我的結果雖不顯著但有檢定力」", A_en:"It can defend a non-significant result as well-powered",
            B:"它與 p 值一一對應，無法提供獨立資訊", B_en:"It is monotone with the p-value and provides no independent information",
            C:"檢定力越高 p 越大", C_en:"Higher power means higher p",
            D:"是 IRB 必要項", D_en:"Required by IRB",
            ans:"B",
            exp:"觀察效應算回的 power 與 p 值單調對應，無法獨立辯護研究的合理性。事前估計、報告效應量 CI 才有意義。",
            exp_en:"Power computed from the observed effect is monotone with p — it cannot independently justify a null finding. Pre-specify and report effect-size CIs." },
          { type:"single",
            stem:"研究計算所需 n=100，預期 dropout 20%，應招募幾人？",
            stem_en:"If you need n=100 and expect 20% dropout, how many should you recruit?",
            A:"100", A_en:"100",
            B:"110", B_en:"110",
            C:"125", C_en:"125",
            D:"200", D_en:"200",
            ans:"C",
            exp:"補償公式 n_recruited = n_needed / (1 − dropout) = 100 / 0.8 = 125。",
            exp_en:"Inflation: n_recruited = n_needed / (1 − dropout) = 100 / 0.8 = 125." },
          { type:"multi",
            stem:"以下哪些是合理的「效應量」來源？（多選）",
            stem_en:"Which are valid sources for the effect size in sample-size calculations? (Multiple)",
            A:"先導性研究 (pilot study)", A_en:"Pilot study",
            B:"已發表的 Meta-analysis", B_en:"Published meta-analyses",
            C:"臨床最小重要差異 (MCID)", C_en:"Minimal clinically important difference (MCID)",
            D:"分析後挑出的最顯著差異", D_en:"The largest observed difference after analysis",
            ans:["A","B","C"],
            exp:"前三項都是事前合理依據；D 等同於 p-hacking，是 IRB 與審稿人會質疑的做法。",
            exp_en:"A, B, C are valid prior sources; D is p-hacking and will be challenged by IRB / reviewers." },
          { type:"tf",
            stem:"是非題：固定 α 與 effect size，提高檢定力 (power) 通常需要更多樣本。",
            stem_en:"True/False: With α and effect size fixed, increasing power requires more samples.",
            ans:"T",
            exp:"四要素互相牽動：固定 α 與 effect size 時，要從 80% 提升到 90% power 必然需要更大的 n。",
            exp_en:"The four parameters constrain each other; raising power from 80% to 90% (α, effect fixed) requires more n." },
          { type:"single",
            stem:"存活研究的樣本量計算，最常用的公式由誰提出？",
            stem_en:"The most common sample-size formula for survival studies was proposed by:",
            A:"Cohen", A_en:"Cohen",
            B:"Schoenfeld (1981)", B_en:"Schoenfeld (1981)",
            C:"Holm", C_en:"Holm",
            D:"Bonferroni", D_en:"Bonferroni",
            ans:"B",
            exp:"Schoenfeld 1981 提出 events ≈ 4(z_α/2 + z_β)² / (lnHR)²，是存活研究的事件數計算依據。",
            exp_en:"Schoenfeld (1981): events ≈ 4(z_α/2 + z_β)² / (lnHR)² — the survival sample-size standard." },
          { type:"single",
            stem:"以下哪個 R 套件最常用於樣本量與檢定力計算？",
            stem_en:"Which R package is most common for sample-size and power calculations?",
            A:"ggplot2", A_en:"ggplot2",
            B:"pwr", B_en:"pwr",
            C:"dplyr", C_en:"dplyr",
            D:"survival", D_en:"survival",
            ans:"B",
            exp:"`pwr` 是 Cohen 公式的 R 實作，涵蓋 t-test、ANOVA、比例、相關等；存活則用 `powerSurvEpi`。",
            exp_en:"`pwr` implements Cohen's formulas in R for t-test, ANOVA, proportions, correlation. Use `powerSurvEpi` for survival." },
          { type:"single",
            stem:"研究設計者常設定 power = 0.80，這代表什麼？",
            stem_en:"Setting power = 0.80 in a study design means:",
            A:"有 80% 的人會存活", A_en:"80% of subjects will survive",
            B:"當真實效應存在時，能偵測到的機率為 80%", B_en:"If a real effect exists, 80% chance of detecting it",
            C:"型一錯誤率為 80%", C_en:"Type I error is 80%",
            D:"效應量為 0.8", D_en:"Effect size is 0.8",
            ans:"B",
            exp:"power = 1 − β = P(拒絕 H₀ | H₁ 為真)；表示在效應確實存在時，研究能偵測出統計顯著差異的機率。",
            exp_en:"power = 1 − β = P(reject H₀ | H₁ true) — the probability of detecting a real effect." }
        ],

        "Step 6：統計假設檢定": [
          { type:"single",
            stem:"p = 0.04 最正確的解讀是？",
            stem_en:"The correct interpretation of p = 0.04 is:",
            A:"虛無假設為真的機率為 4%", A_en:"There's a 4% chance H₀ is true",
            B:"若 H₀ 為真，觀察到此資料或更極端結果的機率為 4%", B_en:"Assuming H₀ true, the probability of seeing data this extreme (or more) is 4%",
            C:"型一錯誤率為 4%", C_en:"Type I error rate is 4%",
            D:"效應量為 0.04", D_en:"Effect size is 0.04",
            ans:"B",
            exp:"p 值是條件機率 P(資料 | H₀ 為真)；它不是 H₀ 為真的機率，也不是型一錯誤率（α 才是）。",
            exp_en:"p is a conditional probability: P(data | H₀ true). It is NOT P(H₀ true), nor is it α." },
          { type:"single",
            stem:"比較三組獨立樣本的連續變數（資料不符常態）最適合的檢定？",
            stem_en:"Best test for three independent groups on a non-normal continuous outcome:",
            A:"One-way ANOVA", A_en:"One-way ANOVA",
            B:"Mann-Whitney U", B_en:"Mann-Whitney U",
            C:"Kruskal-Wallis", C_en:"Kruskal-Wallis",
            D:"Friedman", D_en:"Friedman",
            ans:"C",
            exp:"Kruskal-Wallis 為 ANOVA 的無母數版本，適合 ≥3 獨立組的非常態資料。",
            exp_en:"Kruskal-Wallis is the non-parametric analog of ANOVA for ≥3 independent groups." },
          { type:"single",
            stem:"在 2x2 列聯表中某格期望次數小於 5 時，應改用？",
            stem_en:"In a 2x2 contingency table when an expected count is < 5, prefer:",
            A:"Pearson chi-square", A_en:"Pearson chi-square",
            B:"Fisher's exact test", B_en:"Fisher's exact test",
            C:"McNemar", C_en:"McNemar",
            D:"t-test", D_en:"t-test",
            ans:"B",
            exp:"當期望次數過小，chi-square 的近似不準；Fisher exact 直接計算精確機率，無近似誤差。",
            exp_en:"Chi-square's approximation breaks down at low expected counts; Fisher's exact computes the exact probability." },
          { type:"single",
            stem:"配對前/後血壓比較（連續、常態）應使用？",
            stem_en:"Paired pre/post blood pressure (continuous, normal):",
            A:"Independent t-test", A_en:"Independent t-test",
            B:"Paired t-test", B_en:"Paired t-test",
            C:"Mann-Whitney U", C_en:"Mann-Whitney U",
            D:"Chi-square", D_en:"Chi-square",
            ans:"B",
            exp:"同一受試者前後測量屬於配對資料，應用 paired t-test（檢驗差異是否為 0）。",
            exp_en:"Same subject's pre/post measurements are paired data → paired t-test (test whether differences differ from 0)." },
          { type:"single",
            stem:"比較兩組連續變數，但資料明顯偏態，t-test 是否仍適用？",
            stem_en:"Two-group comparison of a clearly skewed continuous outcome — is t-test still appropriate?",
            A:"絕對不可", A_en:"Absolutely not",
            B:"當 n 各 ≥ 30 時，由中央極限定理，t-test 對輕中度偏態相對穩健；嚴重偏態應改用 Mann-Whitney 或變數轉換", B_en:"With n ≥ 30 per group, CLT makes t-test fairly robust to mild skew; for heavy skew, use Mann-Whitney or transformation",
            C:"只能用 chi-square", C_en:"Only chi-square works",
            D:"應永遠使用 ANOVA", D_en:"Always use ANOVA",
            ans:"B",
            exp:"中央極限定理：大樣本下 t-test 對輕中度偏離常態相對穩健；嚴重偏態 / 小樣本則改用 Mann-Whitney 或對數轉換。",
            exp_en:"CLT: t-test is fairly robust to mild non-normality at large n. For heavy skew or small n, use Mann-Whitney or log-transform." },
          { type:"multi",
            stem:"以下哪些是「配對資料」常用的檢定？（多選）",
            stem_en:"Which tests are commonly used for PAIRED data? (Multiple)",
            A:"Paired t-test", A_en:"Paired t-test",
            B:"Wilcoxon signed-rank test", B_en:"Wilcoxon signed-rank test",
            C:"McNemar test", C_en:"McNemar test",
            D:"Independent two-sample t-test", D_en:"Independent two-sample t-test",
            ans:["A","B","C"],
            exp:"Paired t-test（連續常態）、Wilcoxon signed-rank（連續非常態）、McNemar（配對二元）皆為配對檢定；獨立 t-test 不是。",
            exp_en:"Paired t-test (normal continuous), Wilcoxon signed-rank (non-normal continuous), McNemar (paired binary). Independent t-test is for unpaired data." },
          { type:"tf",
            stem:"是非題：報告統計結果時，效應量 + 95% 信賴區間 比單獨報告 p 值更能傳達證據強度。",
            stem_en:"True/False: Reporting effect size + 95% CI conveys evidence strength better than p-value alone.",
            ans:"T",
            exp:"ASA 2016 與多數現代統計學家明文支持此立場：p 值不能單獨衡量證據強度。",
            exp_en:"The 2016 ASA statement and modern statisticians agree: p alone is not a measure of evidence strength." },
          { type:"single",
            stem:"檢定常態性時，「視覺方法」最常用？",
            stem_en:"Which is the most common visual method to check normality?",
            A:"Bar chart", A_en:"Bar chart",
            B:"Q-Q plot", B_en:"Q-Q plot",
            C:"Pie chart", C_en:"Pie chart",
            D:"Venn diagram", D_en:"Venn diagram",
            ans:"B",
            exp:"Q-Q plot 將樣本分位數對應到理論常態分位數；點接近對角線代表近常態。大樣本下 Shapiro-Wilk 過於敏感，建議優先看圖。",
            exp_en:"Q-Q plot maps sample quantiles to theoretical normal quantiles; points near the diagonal mean approximately normal. Shapiro-Wilk gets oversensitive with large n." },
          { type:"single",
            stem:"關於 Mann-Whitney U test，下列何者正確？",
            stem_en:"Which is correct about the Mann-Whitney U test?",
            A:"是無母數版本的兩組獨立樣本檢定", A_en:"It is the non-parametric version of an independent two-group test",
            B:"要求兩組資料皆呈常態", B_en:"Requires both groups to be normal",
            C:"只能用於配對資料", C_en:"Only works for paired data",
            D:"檢定均值差異", D_en:"Tests difference in means",
            ans:"A",
            exp:"Mann-Whitney U（亦稱 Wilcoxon rank-sum）是兩組獨立樣本的無母數檢定，比較分布位置（不限於均值）。",
            exp_en:"Mann-Whitney U (aka Wilcoxon rank-sum) is the non-parametric test for two independent groups, comparing distribution location." },
          { type:"single",
            stem:"檢定兩連續變數的線性相關（常態）最常用？",
            stem_en:"Most common test for linear correlation between two normal continuous variables:",
            A:"Pearson correlation", A_en:"Pearson correlation",
            B:"Spearman correlation", B_en:"Spearman correlation",
            C:"Kendall tau", C_en:"Kendall tau",
            D:"Cramer V", D_en:"Cramer V",
            ans:"A",
            exp:"Pearson r 假設雙變數常態與線性關係；非常態 / 順序資料用 Spearman 或 Kendall。",
            exp_en:"Pearson r assumes bivariate normality and linearity; for non-normal or ordinal data use Spearman or Kendall." }
        ],

        "Step 7：多重檢定校正": [
          { type:"single",
            stem:"同時進行 10,000 個獨立檢定、α = 0.05，未校正下期望假陽性數為？",
            stem_en:"With 10,000 independent tests at α = 0.05 (uncorrected), expected false positives:",
            A:"50", A_en:"50",
            B:"500", B_en:"500",
            C:"5,000", C_en:"5,000",
            D:"0.05", D_en:"0.05",
            ans:"B",
            exp:"期望 FP ≈ m × α = 10,000 × 0.05 = 500。",
            exp_en:"Expected FP ≈ m × α = 10,000 × 0.05 = 500." },
          { type:"single",
            stem:"FWER 與 FDR 的主要差別是？",
            stem_en:"Main difference between FWER and FDR:",
            A:"兩者控制相同錯誤率", A_en:"They control the same error rate",
            B:"FWER 控制「至少 1 次假陽性的機率」；FDR 控制「假陽性佔顯著結果的期望比例」", B_en:"FWER controls P(≥1 false positive); FDR controls the expected fraction of false positives among rejections",
            C:"FWER 更靈敏", C_en:"FWER is more sensitive",
            D:"兩者完全等價", D_en:"They are equivalent",
            ans:"B",
            exp:"FWER = 一個都不要錯（嚴格）；FDR = 大部分是真的就好（靈敏）。",
            exp_en:"FWER = not even one false call (strict); FDR = most discoveries should be real (sensitive)." },
          { type:"single",
            stem:"RNA-seq 差異表達分析最常用哪種多重檢定校正？",
            stem_en:"Most common multiple-testing correction for RNA-seq DE analysis:",
            A:"Bonferroni", A_en:"Bonferroni",
            B:"Benjamini-Hochberg (BH/FDR)", B_en:"Benjamini-Hochberg (BH/FDR)",
            C:"Holm", C_en:"Holm",
            D:"不校正", D_en:"No correction",
            ans:"B",
            exp:"RNA-seq 屬探索性分析，研究者願接受 ~10% FP 以保留發現 → BH FDR；DESeq2/edgeR 預設即 BH。",
            exp_en:"RNA-seq is exploratory; researchers accept ~10% FPs to retain discoveries → BH FDR. DESeq2/edgeR default to BH." },
          { type:"single",
            stem:"Bonferroni 校正中，比較 m 個檢定時，每個檢定的閾值應設為？",
            stem_en:"In Bonferroni correction with m tests, each test's threshold should be:",
            A:"α × m", A_en:"α × m",
            B:"α / m", B_en:"α / m",
            C:"α²", C_en:"α²",
            D:"√α", D_en:"√α",
            ans:"B",
            exp:"Bonferroni: α* = α / m，將每個檢定的閾值除以總檢定數，確保 FWER ≤ α。",
            exp_en:"Bonferroni: α* = α / m — divide the threshold by the number of tests to keep FWER ≤ α." },
          { type:"single",
            stem:"關於 q-value（Storey 2002），下列何者正確？",
            stem_en:"Which is correct about q-values (Storey 2002)?",
            A:"它估計『真實虛無比例 π₀』後再校正，比 BH 在 π₀ < 1 時更靈敏", A_en:"It estimates the proportion of true nulls (π₀) and is more sensitive than BH when π₀ < 1",
            B:"它就是 Bonferroni", B_en:"It is just Bonferroni",
            C:"它需事先指定組數", C_en:"It requires pre-specified groups",
            D:"它違反 ASA 聲明", D_en:"It violates the ASA statement",
            ans:"A",
            exp:"q-value 在 BH 基礎上額外估計 π₀（真虛無比例），當實際真陰性比例不接近 100% 時更靈敏；R 套件 `qvalue`。",
            exp_en:"q-values build on BH by estimating π₀; more sensitive when most nulls are not true. R: `qvalue`." },
          { type:"multi",
            stem:"以下哪些方法控制 FWER？（多選）",
            stem_en:"Which methods control FWER? (Multiple)",
            A:"Bonferroni", A_en:"Bonferroni",
            B:"Holm-Bonferroni", B_en:"Holm-Bonferroni",
            C:"Šidák", C_en:"Šidák",
            D:"Benjamini-Hochberg", D_en:"Benjamini-Hochberg",
            ans:["A","B","C"],
            exp:"Bonferroni、Holm、Šidák 都控制 FWER；BH 控制 FDR（不同概念）。",
            exp_en:"Bonferroni, Holm, and Šidák control FWER; BH controls FDR — a different concept." },
          { type:"tf",
            stem:"是非題：GWAS 全基因組顯著閾值 5×10⁻⁸ 本質上是對 ~10⁶ 個獨立檢定的 Bonferroni 校正。",
            stem_en:"True/False: The GWAS-wide threshold 5×10⁻⁸ is essentially a Bonferroni correction for ~10⁶ independent tests.",
            ans:"T",
            exp:"人類基因組約 10⁶ 個獨立 LD block；0.05/10⁶ = 5×10⁻⁸，即族群尺度 Bonferroni 閾值。",
            exp_en:"The human genome has ~10⁶ independent LD blocks; 0.05/10⁶ = 5×10⁻⁸ — a genome-wide Bonferroni threshold." },
          { type:"single",
            stem:"R 中執行 BH 校正的最簡單函數是？",
            stem_en:"Simplest R function for BH correction:",
            A:"lm()", A_en:"lm()",
            B:"p.adjust(..., method=\"BH\")", B_en:"p.adjust(..., method=\"BH\")",
            C:"glm()", C_en:"glm()",
            D:"prcomp()", D_en:"prcomp()",
            ans:"B",
            exp:"`p.adjust(pvals, method=\"BH\")` 內建於 R，亦支援 holm、bonferroni、hochberg、BY 等。",
            exp_en:"`p.adjust(pvals, method=\"BH\")` is built-in; also supports holm, bonferroni, hochberg, BY." },
          { type:"single",
            stem:"關於 Bonferroni 校正，下列何者最正確？",
            stem_en:"Which is most correct about Bonferroni correction?",
            A:"非常嚴格、保守，控制 FWER，但在大量檢定時檢定力大幅下降", A_en:"Very strict and conservative, controls FWER, but loses power with many tests",
            B:"控制 FDR，比 BH 更靈敏", B_en:"Controls FDR, more sensitive than BH",
            C:"只能用於 GWAS", C_en:"Only for GWAS",
            D:"等同於不校正", D_en:"Equivalent to no correction",
            ans:"A",
            exp:"Bonferroni 嚴格控制 FWER（一個都不要錯），但對 m 很大時保守至極，會造成大量真陽性被當作假陰性。",
            exp_en:"Bonferroni strictly controls FWER but becomes overly conservative for large m, causing many true positives to be missed." },
          { type:"single",
            stem:"未校正的 RNA-seq 報表中 p < 0.05 的「顯著基因」清單為何不能直接使用？",
            stem_en:"Why can't you directly use a list of 'significant genes' with raw p < 0.05 from RNA-seq?",
            A:"資料太大", A_en:"Too much data",
            B:"做了 ~20,000 個基因檢定，未校正會產生上千假陽性", B_en:"~20,000 gene tests, uncorrected, produce thousands of false positives",
            C:"基因 ID 不對", C_en:"Wrong gene IDs",
            D:"無資料庫支援", D_en:"No database supports it",
            ans:"B",
            exp:"全基因組 ~20,000 個基因，未校正 α=0.05 時期望約 1,000 個假陽性，必須改用 padj/q-value。",
            exp_en:"~20,000 genes × α=0.05 = ~1,000 expected false positives. Must use padj/q-value instead." }
        ],

        "Step 8：偏差、干擾與批次效應": [
          { type:"single",
            stem:"一個變數要成為「干擾因子 (confounder)」，必須同時滿足？",
            stem_en:"To be a confounder, a variable must simultaneously be:",
            A:"與暴露有關、與結果有關、不在因果鏈中介", A_en:"Associated with exposure, associated with outcome, not a mediator",
            B:"與暴露無關、與結果無關", B_en:"Unrelated to both exposure and outcome",
            C:"暴露的後果", C_en:"A consequence of exposure",
            D:"完全隨機", D_en:"Completely random",
            ans:"A",
            exp:"干擾三要件：與 exposure 有關、與 outcome 有關、不是中介或暴露的後果。",
            exp_en:"All three must hold: associated with exposure, with outcome, and NOT a mediator/consequence." },
          { type:"single",
            stem:"已知 batch label 時最常用的批次校正方法是？",
            stem_en:"When batch is known, the most common batch correction is:",
            A:"ComBat", A_en:"ComBat",
            B:"PCA 直接刪除", B_en:"PCA filtering",
            C:"取對數", C_en:"Log transform",
            D:"不校正", D_en:"No correction",
            ans:"A",
            exp:"ComBat (Johnson 2007, sva 套件) 採 empirical Bayes，是已知 batch 變數時的金標準方法。",
            exp_en:"ComBat (Johnson 2007, sva package) uses empirical Bayes — the gold-standard for known-batch correction." },
          { type:"single",
            stem:"完全混淆 (perfectly confounded) 的設計 — 所有 case 在 batch 1、control 在 batch 2 — 可以靠統計校正補救嗎？",
            stem_en:"Can statistical correction rescue a fully confounded batch design (all cases in batch 1, controls in batch 2)?",
            A:"可以，用 ComBat", A_en:"Yes, with ComBat",
            B:"不可以，因為 biology 與 batch 100% 相關、無法分離", B_en:"No — biology and batch are 100% correlated, inseparable",
            C:"可以，加大樣本量", C_en:"Yes, with more samples",
            D:"可以，用 SVA", D_en:"Yes, with SVA",
            ans:"B",
            exp:"當 biology 與 batch 完全相關時，沒有方法能分離；設計階段應平衡分配（每個 batch 含 case 與 control）。",
            exp_en:"When biology and batch are perfectly correlated, no method can separate them. Balance at the design stage." },
          { type:"single",
            stem:"「Berkson 偏倚」屬於哪一類偏差？",
            stem_en:"Berkson's bias is a type of:",
            A:"Selection bias", A_en:"Selection bias",
            B:"Information bias", B_en:"Information bias",
            C:"Confounding", C_en:"Confounding",
            D:"Batch effect", D_en:"Batch effect",
            ans:"A",
            exp:"Berkson 偏倚發生於醫院案例採樣，住院病人比一般人合併更多疾病，是典型的 selection bias。",
            exp_en:"Berkson's bias arises in hospital-based sampling — hospitalized patients have more comorbidities. Classic selection bias." },
          { type:"single",
            stem:"關於 collider（碰撞變數），下列何者正確？",
            stem_en:"Which is correct about colliders?",
            A:"它是兩個變數共同的下游結果，調整它會引入假關聯", A_en:"It is the common effect of two variables; conditioning on it induces spurious associations",
            B:"它是上游干擾因子，必須調整", B_en:"It is an upstream confounder that must be adjusted",
            C:"它是中介變數", C_en:"It is a mediator",
            D:"它與資料無關", D_en:"It is unrelated to data",
            ans:"A",
            exp:"在 DAG A → K ← Y 中，K 是 collider，調整 K 會在原本獨立的 A 與 Y 間引入假關聯（如 COVID 研究中「住院」是常見 collider）。",
            exp_en:"In A → K ← Y, K is a collider; conditioning on K induces a spurious A-Y association (e.g., 'hospitalization' in COVID studies)." },
          { type:"multi",
            stem:"以下哪些屬於 selection bias？（多選）",
            stem_en:"Which are forms of selection bias? (Multiple)",
            A:"Berkson 偏倚（醫院基底）", A_en:"Berkson's bias (hospital-based)",
            B:"Healthy worker effect", B_en:"Healthy worker effect",
            C:"Non-response bias", C_en:"Non-response bias",
            D:"ComBat 批次校正", D_en:"ComBat batch correction",
            ans:["A","B","C"],
            exp:"前三項都屬「誰被招募 / 留下」的選擇問題；ComBat 是技術變數的校正方法，不是 bias 類型。",
            exp_en:"A, B, C are all 'who-gets-in/stays' issues. ComBat is a correction method, not a bias type." },
          { type:"tf",
            stem:"是非題：當 batch 變數未知時，可使用 SVA (Surrogate Variable Analysis) 推斷潛在 batch 並校正。",
            stem_en:"True/False: When batch is unknown, SVA (Surrogate Variable Analysis) can infer latent batch variables and adjust.",
            ans:"T",
            exp:"SVA (Leek & Storey 2007) 推斷未觀察的 surrogate variables 並納入回歸模型，是 batch 未知時的標準方法。",
            exp_en:"SVA (Leek & Storey 2007) infers unobserved surrogate variables and includes them as covariates — standard when batch is unknown." },
          { type:"single",
            stem:"在進行差異表達分析時，如果想「校正」批次效應，正確做法為？",
            stem_en:"When testing for differential expression with batch effects present, the correct approach is to:",
            A:"先用 removeBatchEffect 修改表達值再做檢定", A_en:"First modify expression with removeBatchEffect, then test",
            B:"將 batch 當作共變數納入線性模型", B_en:"Include batch as a covariate in the linear model",
            C:"完全忽略 batch", C_en:"Ignore batch entirely",
            D:"刪除每個 batch 中的一半樣本", D_en:"Delete half the samples in each batch",
            ans:"B",
            exp:"檢定時要在模型中納入 batch 當共變數（如 `~ disease + batch`）。removeBatchEffect 適合可視化，不該直接用其輸出做檢定（不會妥善傳播自由度）。",
            exp_en:"For testing, include batch as a covariate (e.g., `~ disease + batch`). removeBatchEffect is for visualization; using its output for testing mismanages degrees of freedom." },
          { type:"single",
            stem:"在歷史的「咖啡與肺癌」假說中，真正的因子（confounder）是？",
            stem_en:"In the classic 'coffee and lung cancer' association, the true confounder is:",
            A:"咖啡因", A_en:"Caffeine",
            B:"抽菸（吸菸者較常喝咖啡，也較易得肺癌）", B_en:"Smoking (smokers drink more coffee AND get more lung cancer)",
            C:"年齡", C_en:"Age",
            D:"飲水量", D_en:"Water intake",
            ans:"B",
            exp:"早期研究發現喝咖啡與肺癌相關，但喝咖啡者也常抽菸；抽菸同時影響兩者，是經典 confounder 範例。",
            exp_en:"Early studies linked coffee to lung cancer, but coffee drinkers also smoked. Smoking affects both — the classic confounder." },
          { type:"single",
            stem:"以下哪個工具最常用於單細胞 RNA-seq 的 batch 校正？",
            stem_en:"Which is most common for batch correction in single-cell RNA-seq?",
            A:"Harmony / scVI / fastMNN", A_en:"Harmony / scVI / fastMNN",
            B:"GraphPad", B_en:"GraphPad",
            C:"Excel", C_en:"Excel",
            D:"Bonferroni", D_en:"Bonferroni",
            ans:"A",
            exp:"單細胞通常用 latent-space 整合方法：Harmony、scVI、fastMNN、Scanorama 等；ComBat 較適合 bulk。",
            exp_en:"scRNA-seq typically uses latent-space methods: Harmony, scVI, fastMNN, Scanorama. ComBat is more for bulk." }
        ],

        "Step 9：存活分析": [
          { type:"single",
            stem:"關於 censoring（設限），下列何者正確？",
            stem_en:"Which is correct about censoring?",
            A:"它是缺失值，應直接刪除", A_en:"It is missing data and should be dropped",
            B:"它代表『至少存活到 t』的部分資訊，應由 KM/Cox 正確利用", B_en:"It carries the information 'survived at least until t' and is properly handled by KM/Cox",
            C:"它代表事件已發生", C_en:"It means the event occurred",
            D:"它違反 IRB 規範", D_en:"It violates IRB rules",
            ans:"B",
            exp:"censoring 是「研究結束 / 退出時尚未發生事件」，仍有資訊。KM 與 Cox 透過 at-risk 集合正確使用；直接刪除會嚴重低估存活機率。",
            exp_en:"Censoring means 'no event yet at study end / dropout' — still informative. KM and Cox handle it via the at-risk set; dropping biases estimates." },
          { type:"single",
            stem:"Cox 比例風險模型的核心假設是？",
            stem_en:"Cox model's key assumption is:",
            A:"事件時間呈常態", A_en:"Event times are normal",
            B:"比例風險（HR 隨時間維持定值）", B_en:"Proportional hazards (HR constant over time)",
            C:"基線風險為指數分配", C_en:"Baseline hazard is exponential",
            D:"樣本量必須大於 1000", D_en:"Sample size > 1000",
            ans:"B",
            exp:"Cox 是 semi-parametric 模型，不對基線 hazard 形狀做假設，但要求各組 HR 隨時間維持定值（即 PH 假設）。",
            exp_en:"Cox is semi-parametric — no assumption on baseline hazard shape — but requires HR constant over time: the PH assumption." },
          { type:"single",
            stem:"HR = 0.5 應如何解讀？",
            stem_en:"How should HR = 0.5 be interpreted?",
            A:"存活時間多 50%", A_en:"50% longer survival",
            B:"任一時刻的瞬時風險為對照組的一半", B_en:"Instantaneous hazard is half that of control at any time",
            C:"50% 病人會存活", C_en:"50% of patients will survive",
            D:"p 值為 0.5", D_en:"p-value is 0.5",
            ans:"B",
            exp:"HR 是 hazard 的比例（相對風險）。HR=0.5 意指任一時刻處理組的瞬時風險為對照組的 50%；並非絕對存活率。",
            exp_en:"HR is a hazard ratio — relative risk. HR=0.5 means treatment's instantaneous risk is 50% of control's at any time, not absolute survival." },
          { type:"single",
            stem:"當兩條 KM 曲線交叉，log-rank 檢定通常會？",
            stem_en:"When KM curves cross, log-rank typically:",
            A:"檢定力大幅提升", A_en:"Gains power",
            B:"檢定力大幅下降", B_en:"Loses power",
            C:"永遠拒絕 H₀", C_en:"Always rejects H₀",
            D:"沒有影響", D_en:"No effect",
            ans:"B",
            exp:"log-rank 假設 PH。曲線交叉代表早期與晚期 HR 不同，加總時抵消，檢定力大降。改用 RMST 或加權 log-rank。",
            exp_en:"Log-rank assumes PH; crossing curves mean early/late HRs differ and cancel, killing power. Use RMST or weighted log-rank." },
          { type:"single",
            stem:"R 中執行 KM 曲線最常用的函數是？",
            stem_en:"Most common R function for KM curves:",
            A:"lm()", A_en:"lm()",
            B:"survfit() (survival package)", B_en:"survfit() (survival package)",
            C:"glm()", C_en:"glm()",
            D:"prcomp()", D_en:"prcomp()",
            ans:"B",
            exp:"`survival::survfit(Surv(time, status) ~ group, data=...)` 計算 KM 曲線；視覺化用 `survminer::ggsurvplot`。",
            exp_en:"`survival::survfit(Surv(time, status) ~ group, data=...)` computes KM; visualize with `survminer::ggsurvplot`." },
          { type:"multi",
            stem:"以下哪些是 Cox PH 模型常見的「假設違反」處理方法？（多選）",
            stem_en:"Which are common remedies for PH assumption violations? (Multiple)",
            A:"分層 Cox (stratified Cox)", A_en:"Stratified Cox",
            B:"時間相依共變數 (time-varying covariates)", B_en:"Time-varying covariates",
            C:"RMST (Restricted Mean Survival Time)", C_en:"RMST",
            D:"刪除違反假設的樣本", D_en:"Delete samples violating PH",
            ans:["A","B","C"],
            exp:"分層、時間相依共變數與 RMST 都是合法處理；刪除樣本則扭曲結果，不可取。",
            exp_en:"Stratification, time-varying covariates, and RMST are valid; deleting samples distorts results." },
          { type:"tf",
            stem:"是非題：報告 KM 曲線時，應附上 at-risk table（不同時間點還剩多少觀察值）。",
            stem_en:"True/False: KM plots should include an at-risk table showing remaining observations at each time.",
            ans:"T",
            exp:"at-risk 數量少時 KM 末端波動極大；at-risk table 揭露曲線可信度，已成許多生醫期刊的標準要求。",
            exp_en:"With small at-risk sets, KM tails are highly variable; the at-risk table reveals curve reliability — required by many journals." },
          { type:"single",
            stem:"在 Cox 模型中檢驗 PH 假設最常用的方法是？",
            stem_en:"Most common method to check the PH assumption in Cox models:",
            A:"Schoenfeld residuals (R: cox.zph)", A_en:"Schoenfeld residuals (R: cox.zph)",
            B:"Shapiro-Wilk test", B_en:"Shapiro-Wilk test",
            C:"chi-square test", C_en:"chi-square test",
            D:"t-test", D_en:"t-test",
            ans:"A",
            exp:"`cox.zph()` 基於 Schoenfeld residuals 檢定各共變數的 PH 假設；p < 0.05 表示違反。",
            exp_en:"`cox.zph()` uses Schoenfeld residuals to test PH per covariate; p < 0.05 indicates violation." },
          { type:"single",
            stem:"以下何者最適合用於「事件 (event)」？",
            stem_en:"Which is an appropriate 'event' in survival analysis?",
            A:"年齡", A_en:"Age",
            B:"性別", B_en:"Sex",
            C:"癌症復發、死亡、感染等可發生時間點", C_en:"Cancer recurrence, death, infection — a time-stamped occurrence",
            D:"住址", D_en:"Address",
            ans:"C",
            exp:"survival analysis 的「事件」是有明確發生時間點的二元結果（如復發、死亡）。年齡、性別等是共變數，不是事件。",
            exp_en:"Survival 'events' are time-stamped binary outcomes (recurrence, death). Age/sex are covariates, not events." },
          { type:"single",
            stem:"Python 中執行存活分析最常用的套件是？",
            stem_en:"Most common Python package for survival analysis:",
            A:"pandas", A_en:"pandas",
            B:"lifelines", B_en:"lifelines",
            C:"scikit-image", C_en:"scikit-image",
            D:"keras", D_en:"keras",
            ans:"B",
            exp:"`lifelines` 提供 KaplanMeierFitter、CoxPHFitter、log-rank 與 PH 檢驗等完整功能；另有 `scikit-survival`。",
            exp_en:"`lifelines` offers KaplanMeierFitter, CoxPHFitter, log-rank, and PH checks; also see `scikit-survival`." }
        ]

      },
      "進階研究主題": {

        "Advanced：因果推論": [
          { type:"single",
            stem:"在 DAG 「A → M → Y」 中，應該調整 M 嗎？",
            stem_en:"In the DAG A → M → Y, should you adjust for M?",
            A:"應該調整", A_en:"Yes, adjust",
            B:"不應該 — M 是中介，調整它會切斷因果路徑", B_en:"No — M is a mediator; adjusting blocks the causal path",
            C:"只在大樣本下調整", C_en:"Only with large n",
            D:"看 p 值決定", D_en:"Depends on p-value",
            ans:"B",
            exp:"中介變數調整會切斷 A→Y 的因果路徑，導致總效應估計偏低（甚至完全消失）。",
            exp_en:"Adjusting for a mediator blocks the A→Y path, biasing the total effect toward zero." },
          { type:"single",
            stem:"傾向分數 (propensity score) 方法的最大限制是？",
            stem_en:"Propensity score's biggest limitation:",
            A:"計算太慢", A_en:"Slow computation",
            B:"無法處理未觀察的干擾因子", B_en:"Cannot handle unmeasured confounders",
            C:"只能用 logistic regression", C_en:"Only works with logistic regression",
            D:"不能與 IPTW 結合", D_en:"Incompatible with IPTW",
            ans:"B",
            exp:"PS 只平衡『觀察到』的共變數；未觀察混淆需配合敏感度分析（E-value）或 IV 方法。",
            exp_en:"PS only balances observed covariates. Unmeasured confounding needs sensitivity analysis (E-value) or IV methods." },
          { type:"single",
            stem:"孟德爾隨機化 (MR) 中，SNP 作為工具變數 (IV) 的優勢是？",
            stem_en:"Why are SNPs good instrumental variables in Mendelian randomization?",
            A:"SNP 與表型相關性極高", A_en:"SNPs correlate strongly with phenotype",
            B:"受精時隨機分配、一生固定，與行為混淆獨立", B_en:"Randomly assigned at conception, fixed for life, independent of behavioral confounders",
            C:"每個 SNP 都是因果變異", C_en:"Every SNP is causal",
            D:"SNP 直接影響疾病", D_en:"SNPs directly cause disease",
            ans:"B",
            exp:"SNP 在受精時隨機分配（Mendel 第二定律）、一生固定且不受暴露反向影響，與大多數行為/社經混淆獨立，類似 RCT 的隨機分配。",
            exp_en:"SNPs are randomly assigned at conception (Mendel's 2nd law), fixed for life (no reverse causation), and independent of most behavioral confounders." },
          { type:"single",
            stem:"工具變數 (IV) 必須滿足哪三項假設？",
            stem_en:"Which three assumptions must an instrumental variable satisfy?",
            A:"相關性、排除限制、與混淆獨立", A_en:"Relevance, exclusion restriction, independence from confounders",
            B:"大樣本、常態、線性", B_en:"Large sample, normal, linear",
            C:"獨立、相同分布、可微", C_en:"i.i.d. and differentiable",
            D:"隨機、雙盲、安慰劑", D_en:"Random, double-blind, placebo",
            ans:"A",
            exp:"IV 三條件：(1) 與暴露相關（relevance），(2) 排除限制（exclusion restriction，只透過暴露影響結果），(3) 與混淆獨立。",
            exp_en:"IV must satisfy: (1) relevance (associated with exposure), (2) exclusion restriction (affects outcome only through exposure), (3) independence from confounders." },
          { type:"multi",
            stem:"以下哪些屬於因果推論常用方法？（多選）",
            stem_en:"Which are common causal-inference methods? (Multiple)",
            A:"Propensity score matching", A_en:"Propensity score matching",
            B:"Instrumental variable / 2SLS", B_en:"Instrumental variable / 2SLS",
            C:"Difference-in-Differences (DiD)", C_en:"Difference-in-Differences (DiD)",
            D:"Pearson correlation", D_en:"Pearson correlation",
            ans:["A","B","C"],
            exp:"PS matching、IV/2SLS、DiD、RDD、MR、G-methods 等皆為因果推論工具；Pearson 只描述相關，不能直接做因果推論。",
            exp_en:"PS, IV/2SLS, DiD, RDD, MR, G-methods are causal tools. Pearson only describes correlation." },
          { type:"tf",
            stem:"是非題：在 DAG 中，調整一個 collider 變數會在原本獨立的兩變數間引入假關聯。",
            stem_en:"True/False: Conditioning on a collider induces a spurious association between two otherwise-independent variables.",
            ans:"T",
            exp:"這是 Pearl 因果推論的核心結果之一。實務上常見於 case-control 或選擇性樣本中。",
            exp_en:"A core result in Pearl's causal inference, common in case-control or selected samples." },
          { type:"single",
            stem:"執行 MR 分析時，為什麼必須做敏感度分析（如 MR-Egger、weighted median）？",
            stem_en:"Why are sensitivity analyses (MR-Egger, weighted median) essential in MR?",
            A:"加快計算", A_en:"Speed up computation",
            B:"檢驗 horizontal pleiotropy 等違反排除限制的可能", B_en:"Check for horizontal pleiotropy and other exclusion-restriction violations",
            C:"提高 p 值", C_en:"Inflate p-values",
            D:"美觀考量", D_en:"Aesthetic",
            ans:"B",
            exp:"MR 最常見的假設違反是 horizontal pleiotropy（SNP 透過其他路徑影響結果）。MR-Egger intercept、weighted median、MR-PRESSO 等可檢測並提供穩健估計。",
            exp_en:"Horizontal pleiotropy is MR's most common violation. MR-Egger intercept, weighted median, MR-PRESSO detect and robustify against it." },
          { type:"single",
            stem:"線上工具 DAGitty 主要用來？",
            stem_en:"What is the online tool DAGitty mainly used for?",
            A:"執行 RNA-seq", A_en:"Run RNA-seq",
            B:"繪製 DAG 並自動建議『需要調整哪些變數』", B_en:"Draw DAGs and auto-suggest which variables to adjust for",
            C:"做 Meta 分析", C_en:"Perform meta-analysis",
            D:"基因註釋", D_en:"Gene annotation",
            ans:"B",
            exp:"dagitty.net 提供互動式 DAG 繪製，依 back-door criterion 自動建議調整變數集合。",
            exp_en:"dagitty.net offers interactive DAG drawing and auto-recommends adjustment sets via the back-door criterion." },
          { type:"single",
            stem:"在 RCT 中為什麼可以「不必擔心 confounder」？",
            stem_en:"Why don't RCTs typically worry about confounders?",
            A:"樣本量大", A_en:"Large sample size",
            B:"隨機分配平衡所有已知與未知共變數的期望值", B_en:"Randomization balances both known and unknown covariates in expectation",
            C:"使用最新統計方法", C_en:"Use cutting-edge stats",
            D:"IRB 規定", D_en:"IRB rule",
            ans:"B",
            exp:"隨機化讓兩組在所有共變數（含未測量的）期望值相等，這正是 RCT 為何被視為因果推論金標準的原因。",
            exp_en:"Randomization equalizes both groups on all covariates (including unmeasured) in expectation — the reason RCTs are the causal gold standard." },
          { type:"single",
            stem:"以下哪個 Python 套件專門做因果推論？",
            stem_en:"Which Python package specializes in causal inference?",
            A:"DoWhy", A_en:"DoWhy",
            B:"pandas", B_en:"pandas",
            C:"scikit-image", C_en:"scikit-image",
            D:"requests", D_en:"requests",
            ans:"A",
            exp:"DoWhy（Microsoft）整合 Pearl 的識別性檢查與 Rubin 的估計，含 refutation tests；另有 EconML、CausalML。",
            exp_en:"DoWhy (Microsoft) combines Pearl's identification with Rubin-style estimation and refutation tests; also EconML, CausalML." }
        ],

        "Advanced：Meta 分析": [
          { type:"single",
            stem:"I² = 80% 應如何解讀？",
            stem_en:"How should I² = 80% be interpreted?",
            A:"80% 研究效應為陽性", A_en:"80% of studies are positive",
            B:"大幅異質性——研究間真效應差異顯著", B_en:"Substantial heterogeneity — true effects vary across studies",
            C:"合併效應有 80% 信心", C_en:"80% confidence in pooled effect",
            D:"80% 樣本已招募", D_en:"80% recruitment achieved",
            ans:"B",
            exp:"I² = 研究間變異佔總變異的比例；80% 表示大幅異質性，應做次群組或 meta-regression 探究原因。",
            exp_en:"I² = fraction of total variance due to between-study heterogeneity; 80% is substantial. Investigate via subgroup/meta-regression." },
          { type:"single",
            stem:"漏斗圖 (funnel plot) 不對稱通常暗示？",
            stem_en:"An asymmetric funnel plot typically suggests:",
            A:"大樣本問題", A_en:"Issues with large samples",
            B:"可能存在發表偏倚或小規模研究效應", B_en:"Possible publication bias or small-study effects",
            C:"隨機效應模型錯誤", C_en:"Wrong random-effects model",
            D:"研究數不足", D_en:"Too few studies",
            ans:"B",
            exp:"漏斗圖橫軸效應、縱軸精確度；非對稱常見原因是小規模、效應陰性的研究未發表。配合 Egger 檢定。",
            exp_en:"Funnel plots plot effect vs precision; asymmetry often signals missing small null studies. Confirm with Egger's test." },
          { type:"single",
            stem:"何時應優先使用「隨機效應」模型？",
            stem_en:"When should you prefer a random-effects model?",
            A:"所有研究設計完全相同時", A_en:"All studies are identical",
            B:"研究人口、處置、設計有合理差異時", B_en:"Studies differ reasonably in populations, interventions, designs",
            C:"資料為基因組學", C_en:"Data is genomic",
            D:"永遠不該用", D_en:"Never",
            ans:"B",
            exp:"當不確定時 Cochrane 建議預設隨機效應，因現實研究幾乎都有差異。固定效應假設過嚴。",
            exp_en:"Cochrane recommends random-effects by default — real studies almost always differ. Fixed-effect's assumption is too strict." },
          { type:"single",
            stem:"GRADE 中，RCT 起始評為哪一級？",
            stem_en:"In GRADE, RCTs start at which level?",
            A:"High", A_en:"High",
            B:"Moderate", B_en:"Moderate",
            C:"Low", C_en:"Low",
            D:"Very Low", D_en:"Very Low",
            ans:"A",
            exp:"RCT 因設計強度起始於 High，可因偏倚、不一致、間接性、精確度、發表偏倚下調；觀察性研究起始為 Low。",
            exp_en:"RCTs start at High due to design strength; can be downgraded by bias, inconsistency, indirectness, imprecision, publication bias. Observational studies start at Low." },
          { type:"single",
            stem:"森林圖 (forest plot) 中，方塊大小通常代表？",
            stem_en:"In a forest plot, the square size typically represents:",
            A:"作者人數", A_en:"Number of authors",
            B:"該研究的權重（通常正比於 1/變異數）", B_en:"Study weight (typically ∝ 1/variance)",
            C:"出版年份", C_en:"Year of publication",
            D:"期刊 IF", D_en:"Journal impact factor",
            ans:"B",
            exp:"森林圖的方塊大小反映該研究的「權重」，通常正比於 1/variance（精確度高的研究方塊較大）。",
            exp_en:"Square size reflects study weight, typically proportional to 1/variance (precise studies get larger squares)." },
          { type:"multi",
            stem:"以下哪些是評估或校正發表偏倚的方法？（多選）",
            stem_en:"Which methods assess or correct publication bias? (Multiple)",
            A:"Funnel plot", A_en:"Funnel plot",
            B:"Egger's regression test", B_en:"Egger's regression test",
            C:"Trim-and-fill", C_en:"Trim-and-fill",
            D:"Cohen's d", D_en:"Cohen's d",
            ans:["A","B","C"],
            exp:"Funnel plot、Egger test、Trim-and-fill、PET-PEESE、Selection models 都是評估/敏感度分析工具；Cohen's d 是效應量度，與發表偏倚無關。",
            exp_en:"Funnel plot, Egger test, Trim-and-fill, PET-PEESE, selection models — all bias diagnostics. Cohen's d is an effect size." },
          { type:"tf",
            stem:"是非題：Meta 分析所有研究合併計算後得到的「合併效應 (pooled effect)」總是比單一研究的估計更精確。",
            stem_en:"True/False: The pooled effect from a meta-analysis is always more precise than any single study's estimate.",
            ans:"T",
            exp:"合併數據累積樣本量，標準誤通常較小；但這只在「研究品質相似」的前提下才有意義，否則可能是『精確但有偏倚』。",
            exp_en:"Pooling accumulates sample size, typically reducing SE. But this only matters if study quality is similar — otherwise it can be 'precise but biased.'" },
          { type:"single",
            stem:"R 中執行 Meta 分析最常用的兩個套件是？",
            stem_en:"Two most common R packages for meta-analysis:",
            A:"ggplot2 / dplyr", A_en:"ggplot2 / dplyr",
            B:"meta / metafor", B_en:"meta / metafor",
            C:"survival / lifelines", C_en:"survival / lifelines",
            D:"Seurat / Scanpy", D_en:"Seurat / Scanpy",
            ans:"B",
            exp:"`meta`（簡潔語法）、`metafor`（功能完整）為兩大主流 Meta 分析套件；Python 端可用 `PythonMeta`。",
            exp_en:"`meta` (concise syntax) and `metafor` (full-featured) are the two main R MA packages; Python has `PythonMeta`." },
          { type:"single",
            stem:"關於 τ²（tau-squared），下列何者正確？",
            stem_en:"Which is correct about τ² (tau-squared)?",
            A:"它是研究內變異", A_en:"It is within-study variance",
            B:"它是研究間真效應變異數的估計", B_en:"It is the estimated between-study true-effect variance",
            C:"它與異質性無關", C_en:"Unrelated to heterogeneity",
            D:"它只用在固定效應", D_en:"Used only in fixed-effects",
            ans:"B",
            exp:"τ² 為隨機效應模型下的研究間真效應變異數，可由 REML 或 DerSimonian-Laird 估計；√τ² 可用於建構預測區間。",
            exp_en:"τ² is the between-study true-effect variance under random effects, estimated by REML or DerSimonian-Laird; √τ² gives the prediction interval." },
          { type:"single",
            stem:"以下哪一個指引專門針對「系統性回顧與 Meta-analysis」的報告？",
            stem_en:"Which reporting guideline is specifically for systematic reviews and meta-analyses?",
            A:"CONSORT", A_en:"CONSORT",
            B:"STROBE", B_en:"STROBE",
            C:"PRISMA", C_en:"PRISMA",
            D:"ARRIVE", D_en:"ARRIVE",
            ans:"C",
            exp:"PRISMA 為 SR/MA 的標準報告指引；CONSORT 為 RCT、STROBE 為觀察性研究、ARRIVE 為動物實驗。",
            exp_en:"PRISMA is for SR/MA; CONSORT for RCTs; STROBE for observational; ARRIVE for animal research." }
        ],

        "Advanced：可重現研究": [
          { type:"single",
            stem:"「Computational reproducibility（計算重現性）」最基本的定義是？",
            stem_en:"Most basic definition of computational reproducibility:",
            A:"不同樣本能得到相同結果", A_en:"Same result on new samples",
            B:"同樣資料 + 同樣程式碼 → 同樣結果", B_en:"Same data + same code → same result",
            C:"不同方法 → 同樣結論", C_en:"Different methods → same conclusion",
            D:"不同實驗室 → 同樣結果", D_en:"Different labs → same result",
            ans:"B",
            exp:"這是重現性的最低門檻：任何人取得你的資料和程式碼都能得到同樣輸出。",
            exp_en:"The floor: anyone with your data and code reproduces your output." },
          { type:"single",
            stem:"HPC 環境最常用哪種容器系統？",
            stem_en:"Most common container system on HPC clusters:",
            A:"Docker", A_en:"Docker",
            B:"Singularity / Apptainer", B_en:"Singularity / Apptainer",
            C:"VMware", C_en:"VMware",
            D:"不使用容器", D_en:"No containers",
            ans:"B",
            exp:"HPC 通常不允許 root 權限；Singularity/Apptainer 是不需 root 的替代方案，且能讀 Docker image。",
            exp_en:"HPC disallows root; Singularity/Apptainer is rootless and can pull Docker images." },
          { type:"single",
            stem:"處理過的「分析結果資料」應該存放在？",
            stem_en:"Processed analysis-ready data should be deposited at:",
            A:"私人電腦", A_en:"Local hard drive",
            B:"Zenodo / FigShare 等公開資料庫並取得 DOI", B_en:"Public repository like Zenodo / FigShare with DOI",
            C:"PDF 附錄", C_en:"PDF supplement",
            D:"完全不公開", D_en:"Do not share",
            ans:"B",
            exp:"Zenodo/FigShare 提供永久 DOI、版本控管與 metadata 範本，符合 FAIR 原則。",
            exp_en:"Zenodo/FigShare provide persistent DOIs, versioning, metadata — meeting FAIR principles." },
          { type:"single",
            stem:"在生資專案中，最常用的「工作流引擎」之一是？",
            stem_en:"A commonly used bioinformatics workflow engine is:",
            A:"Snakemake", A_en:"Snakemake",
            B:"Photoshop", B_en:"Photoshop",
            C:"Excel macro", C_en:"Excel macro",
            D:"Microsoft Word", D_en:"Microsoft Word",
            ans:"A",
            exp:"Snakemake 與 Nextflow 是兩大生資工作流引擎，可從 FASTQ 一鍵跑到結果，支援容器與雲端執行。",
            exp_en:"Snakemake and Nextflow are the two main bioinformatics workflow engines — from FASTQ to results, container- and cloud-ready." },
          { type:"single",
            stem:"以下哪個是 R 專案的環境鎖定工具？",
            stem_en:"Which tool locks the R package environment for a project?",
            A:"conda", A_en:"conda",
            B:"renv", B_en:"renv",
            C:"poetry", C_en:"poetry",
            D:"npm", D_en:"npm",
            ans:"B",
            exp:"renv 為 R 專案專屬的環境鎖定，生成 renv.lock 紀錄套件版本；Python 端對應為 conda/poetry/uv。",
            exp_en:"renv is project-level lockfile for R, producing renv.lock; Python equivalents are conda/poetry/uv." },
          { type:"multi",
            stem:"以下哪些屬於可重現研究的「四層工具」？（多選）",
            stem_en:"Which belong to the 'four-layer toolkit' of reproducibility? (Multiple)",
            A:"版本控制 (Git)", A_en:"Version control (Git)",
            B:"環境管理 (conda / renv)", B_en:"Environment management (conda / renv)",
            C:"容器化 (Docker / Singularity)", C_en:"Containers (Docker / Singularity)",
            D:"工作流 (Snakemake / Nextflow)", D_en:"Workflows (Snakemake / Nextflow)",
            ans:["A","B","C","D"],
            exp:"四層皆是必備：Git 控版、conda/renv 管環境、容器固化系統、workflow 串接整個流程。",
            exp_en:"All four are essential: Git for versioning, conda/renv for environment, containers for system, workflows for pipelining." },
          { type:"tf",
            stem:"是非題：在專案目錄中，raw 與 processed 資料應分開存放；raw 視為唯讀。",
            stem_en:"True/False: In a project, raw and processed data should be separated; raw should be treated as read-only.",
            ans:"T",
            exp:"raw 必須維持原貌（萬一處理錯誤可回到起點）；processed 是程式碼 + raw 的衍生物，可隨時重建。",
            exp_en:"Raw must stay untouched (so you can re-run from scratch); processed is a code-derived artifact, regeneratable." },
          { type:"single",
            stem:"取代 R Markdown 與 Jupyter Book、支援 R / Python / Julia / Observable 的新一代動態文件系統是？",
            stem_en:"Next-gen dynamic document system supporting R/Python/Julia/Observable, replacing R Markdown and Jupyter Book:",
            A:"Quarto", A_en:"Quarto",
            B:"Excel", B_en:"Excel",
            C:"Word", C_en:"Word",
            D:"PowerPoint", D_en:"PowerPoint",
            ans:"A",
            exp:"Quarto 由 RStudio (Posit) 推出，可同時支援多語言並輸出 HTML/PDF/DOCX/書籍/網站；2022 起取代 R Markdown 成為新標準。",
            exp_en:"Quarto (Posit) supports multi-language and outputs HTML/PDF/DOCX/books/sites; the new standard since 2022, succeeding R Markdown." },
          { type:"single",
            stem:"以下哪個 NIH 政策要求 2024 起所有 NIH-funded 論文需公開存取？",
            stem_en:"Which NIH policy requires all NIH-funded papers to be publicly accessible since 2024?",
            A:"HIPAA", A_en:"HIPAA",
            B:"NIH Public Access Policy", B_en:"NIH Public Access Policy",
            C:"GDPR", C_en:"GDPR",
            D:"Common Rule", D_en:"Common Rule",
            ans:"B",
            exp:"NIH Public Access Policy 自 2024 起強制要求所有 NIH-funded 論文於接受發表後立即可公開存取（PMC 自動存檔）。",
            exp_en:"Since 2024, NIH Public Access Policy mandates immediate open access for all NIH-funded papers (PMC auto-archive)." },
          { type:"single",
            stem:"以下哪個是「容器化」研究的最主要益處？",
            stem_en:"What is the main benefit of containerizing research?",
            A:"提高 IF", A_en:"Boost IF",
            B:"打包 OS、函式庫、工具與環境，確保多年後仍能跑", B_en:"Bundle OS, libs, tools, and environment — ensures it still runs years later",
            C:"美觀考量", C_en:"Aesthetic",
            D:"加快寫稿", D_en:"Speeds up writing",
            ans:"B",
            exp:"容器把整個系統（OS + 函式庫 + 工具 + 環境）打包成單一映像檔，避免「在我電腦能跑」的詛咒，讓研究 5 年、10 年後仍可重現。",
            exp_en:"Containers bundle the whole system (OS + libs + tools + env) into a single image — escaping the 'works on my machine' curse and preserving reproducibility years later." }
        ],

        "Advanced：數據視覺化": [
          { type:"single",
            stem:"連續資料分布最適合呈現方式為？",
            stem_en:"Best way to visualize a continuous distribution:",
            A:"3D 長條圖", A_en:"3D bar chart",
            B:"histogram / violin / boxplot", B_en:"histogram / violin / boxplot",
            C:"圓餅圖", C_en:"Pie chart",
            D:"堆疊長條", D_en:"Stacked bar",
            ans:"B",
            exp:"連續資料分布應呈現整體形狀（histogram/density）或四分位（boxplot/violin），不要只給平均值或長條。",
            exp_en:"Distributions need to show shape (histogram/density) or quartiles (boxplot/violin) — not just means or bars." },
          { type:"single",
            stem:"為什麼建議避免使用 rainbow / jet 色板？",
            stem_en:"Why avoid rainbow / jet palettes?",
            A:"太鮮豔", A_en:"Too vibrant",
            B:"感知亮度不均勻、色盲不友善", B_en:"Non-uniform perceptual brightness, colorblind-unfriendly",
            C:"檔案太大", C_en:"Large file size",
            D:"只能用紅綠", D_en:"Only red/green",
            ans:"B",
            exp:"rainbow 在亮度上不單調 → 數值大小感知扭曲；對紅綠色盲使用者也不友善。Viridis 是業界標準替代。",
            exp_en:"Rainbow's luminance is non-monotonic, distorting perceived magnitude and failing colorblind users. Viridis is the standard alternative." },
          { type:"single",
            stem:"表達 log fold-change (有正負方向) 應使用哪種色板？",
            stem_en:"Best palette for log fold-change (signed):",
            A:"順序色 (viridis)", A_en:"Sequential (viridis)",
            B:"發散色 (diverging)，白色置 0", B_en:"Diverging, with white at 0",
            C:"分類色 (Set1)", C_en:"Qualitative (Set1)",
            D:"黑白", D_en:"Black & white",
            ans:"B",
            exp:"logFC 有正負方向，應用 diverging 色板（如 RdBu_r、coolwarm）並讓白色對齊 0，避免方向視覺混淆。",
            exp_en:"Use a diverging palette (RdBu_r, coolwarm) with white aligned to 0 for signed data — otherwise direction becomes visually misleading." },
          { type:"single",
            stem:"為什麼 KM 曲線應附 at-risk table？",
            stem_en:"Why should KM curves include an at-risk table?",
            A:"期刊規定", A_en:"Journal rule",
            B:"標示每個時間點剩多少觀察值，揭露曲線可信度", B_en:"Shows remaining observations at each time, revealing curve reliability",
            C:"美觀", C_en:"Aesthetic",
            D:"取代 p 值", D_en:"Replaces p-value",
            ans:"B",
            exp:"at-risk 數量少時 KM 末端波動極大，必須揭示給讀者，越來越多生醫期刊將其列為必備。",
            exp_en:"With small at-risk sets, KM tails are highly variable — readers need this info. Increasingly required by journals." },
          { type:"single",
            stem:"關於「dynamite plot」（只畫平均值與一條誤差線的長條圖），何者正確？",
            stem_en:"Which is correct about 'dynamite plots' (bar with mean ± SD)?",
            A:"是最佳的科學圖表", A_en:"The best scientific chart",
            B:"隱藏資料分布、樣本量與離群值，應改用 boxplot+jitter 或 violin", B_en:"Hides distribution, sample size, outliers — use boxplot+jitter or violin instead",
            C:"是 Nature 期刊推薦", C_en:"Recommended by Nature",
            D:"可以呈現中位數", D_en:"Shows median",
            ans:"B",
            exp:"Weissgerber et al. (PLoS Biol 2015) 點名 dynamite plot 為「隱藏資料」的代表；現代期刊鼓勵 boxplot+jitter 或 violin。",
            exp_en:"Weissgerber et al. (PLoS Biol 2015) called out dynamite plots for hiding data; journals now favor boxplot+jitter or violin." },
          { type:"multi",
            stem:"以下哪些屬於「不該做的視覺化模式」？（多選）",
            stem_en:"Which are visualization anti-patterns? (Multiple)",
            A:"3D 圓餅 / 3D 長條", A_en:"3D pie / 3D bar",
            B:"無 sample size 的 boxplot", B_en:"Boxplot without n",
            C:"y 軸從非零開始放大微小差異", C_en:"Y-axis starting from non-zero to inflate small differences",
            D:"使用 viridis 連續色板", D_en:"Using viridis sequential palette",
            ans:["A","B","C"],
            exp:"3D 扭曲面積、缺 n 看不出統計可信度、斷裂 y 軸是經典誤導；viridis 是好做法。",
            exp_en:"3D distorts area; missing n hides reliability; broken y-axis misleads. Viridis is the correct choice." },
          { type:"tf",
            stem:"是非題：對紅綠色盲使用者友善的視覺化應「同時」用顏色與形狀（或標籤、紋理）傳達資訊。",
            stem_en:"True/False: Colorblind-friendly visualization should use both color AND shape (or labels, textures).",
            ans:"T",
            exp:"~8% 男性、0.5% 女性有紅綠色盲；不要單獨依賴顏色，應配合形狀、紋理或直接標籤。",
            exp_en:"~8% of men, 0.5% of women have red-green color blindness. Never rely on color alone — combine with shape/pattern/labels." },
          { type:"single",
            stem:"R 中最普及的繪圖系統「ggplot2」基於什麼理論？",
            stem_en:"The R package ggplot2 is based on which theory?",
            A:"Grammar of Graphics（Wilkinson 1999）", A_en:"Grammar of Graphics (Wilkinson 1999)",
            B:"Bayes 推論", B_en:"Bayesian inference",
            C:"Cox 模型", C_en:"Cox model",
            D:"Fisher 散布", D_en:"Fisher distribution",
            ans:"A",
            exp:"ggplot2 由 Hadley Wickham 基於 Wilkinson 的 Grammar of Graphics 實作，把圖層化思維帶入 R 統計繪圖。",
            exp_en:"ggplot2, by Hadley Wickham, implements Wilkinson's Grammar of Graphics — layered thinking for statistical plotting in R." },
          { type:"single",
            stem:"差異基因 (DE) 結果最常用哪一種圖呈現？",
            stem_en:"Which plot is most common for differential expression (DE) results?",
            A:"Volcano plot（logFC vs −log10 p）", A_en:"Volcano plot (logFC vs −log10 p)",
            B:"3D pie", B_en:"3D pie",
            C:"圓餅圖", C_en:"Pie chart",
            D:"流程圖", D_en:"Flow chart",
            ans:"A",
            exp:"Volcano plot 將每個基因依 logFC（x）與 -log10 p（y）繪點，能一眼看出顯著且效應強的基因。MA plot 也常見。",
            exp_en:"Volcano plots map each gene by logFC (x) vs -log10 p (y), revealing significant and large-effect genes at a glance. MA plots are also common." },
          { type:"single",
            stem:"關於誤導性圖表中的「斷裂 y 軸」(broken y-axis)，何者正確？",
            stem_en:"Which is correct about 'broken y-axis' as a misleading practice?",
            A:"可隨意使用", A_en:"Use freely",
            B:"會放大微小差異、誤導讀者；極端範圍應改用對數刻度", B_en:"Inflates small differences misleadingly; use log scale for extreme ranges instead",
            C:"是 ggplot2 預設", C_en:"It is ggplot2 default",
            D:"與資料無關", D_en:"Unrelated to data",
            ans:"B",
            exp:"斷裂 y 軸放大微小差異是經典誤導手法；除非極端範圍才考慮，且優先用對數刻度而非斷裂。",
            exp_en:"Broken y-axes inflate minor differences — a classic deception. For extreme ranges, prefer log scale over breaking the axis." }
        ],

        "Advanced：科學寫作與發表": [
          { type:"single",
            stem:"IMRaD 結構中的「D」代表？",
            stem_en:"What does the 'D' in IMRaD stand for?",
            A:"Data", A_en:"Data",
            B:"Discussion", B_en:"Discussion",
            C:"Design", C_en:"Design",
            D:"Diagnosis", D_en:"Diagnosis",
            ans:"B",
            exp:"IMRaD = Introduction / Methods / Results / and Discussion，是生醫論文的標準結構。",
            exp_en:"IMRaD = Introduction / Methods / Results / and Discussion — the standard biomedical paper structure." },
          { type:"single",
            stem:"觀察性研究 (cohort/case-control/cross-sectional) 的報告指引是？",
            stem_en:"Reporting guideline for observational studies (cohort/case-control/cross-sectional):",
            A:"CONSORT", A_en:"CONSORT",
            B:"STROBE", B_en:"STROBE",
            C:"PRISMA", C_en:"PRISMA",
            D:"ARRIVE", D_en:"ARRIVE",
            ans:"B",
            exp:"STROBE 為觀察性研究的標準報告指引；CONSORT 為 RCT、PRISMA 為 SR/MA、ARRIVE 為動物研究。",
            exp_en:"STROBE for observational; CONSORT for RCT; PRISMA for SR/MA; ARRIVE for animal research." },
          { type:"single",
            stem:"ICMJE 四項作者準則中，下列哪項<u>不</u>列入？",
            stem_en:"Which is NOT one of ICMJE's four authorship criteria?",
            A:"對研究有實質貢獻", A_en:"Substantial contribution",
            B:"參與撰寫或關鍵修訂", B_en:"Drafting / critical revision",
            C:"提供經費支持", C_en:"Provided funding only",
            D:"同意最終版本並負責", D_en:"Final approval and accountability",
            ans:"C",
            exp:"僅提供經費不能列為作者（應放 Acknowledgements）。ICMJE 四準則：實質貢獻、撰寫/修訂、同意版本、負責。",
            exp_en:"Funding alone doesn't grant authorship (acknowledge instead). ICMJE: substantial contribution, drafting, final approval, accountability." },
          { type:"single",
            stem:"預印本 (preprint) 最主要的價值是？",
            stem_en:"Preprint's main value:",
            A:"取代同儕審查", A_en:"Replaces peer review",
            B:"快速建立優先權與取得社群回饋", B_en:"Establishes priority and gathers feedback quickly",
            C:"省去寫期刊版本", C_en:"Skips the journal version",
            D:"提高 IF", D_en:"Boosts IF",
            ans:"B",
            exp:"預印本讓研究在審查期間就被引用、批評、修正；它不取代同儕審查，而是補位於審查之前。",
            exp_en:"Preprints expose research during peer review for early citation, critique, and refinement — they don't replace peer review." },
          { type:"single",
            stem:"以下哪個是「永久學者識別碼」，可全球唯一識別研究者？",
            stem_en:"Which is a permanent global researcher identifier?",
            A:"DOI", A_en:"DOI",
            B:"ORCID", B_en:"ORCID",
            C:"IF", C_en:"IF",
            D:"PMID", D_en:"PMID",
            ans:"B",
            exp:"ORCID (Open Researcher and Contributor ID) 提供每位學者一個永久全球識別碼，避免姓名重複帶來的歸屬混淆。",
            exp_en:"ORCID provides each researcher a permanent global ID, avoiding name-collision attribution issues." },
          { type:"multi",
            stem:"以下哪些是有效的 EQUATOR 報告指引？（多選）",
            stem_en:"Which are valid EQUATOR reporting guidelines? (Multiple)",
            A:"CONSORT（RCT）", A_en:"CONSORT (RCT)",
            B:"STROBE（觀察性）", B_en:"STROBE (Observational)",
            C:"TRIPOD+AI（預測模型）", C_en:"TRIPOD+AI (Prediction)",
            D:"HIPAA（隱私）", D_en:"HIPAA (Privacy)",
            ans:["A","B","C"],
            exp:"CONSORT、STROBE、TRIPOD+AI 都是 EQUATOR 收錄的報告指引；HIPAA 是法規不是報告指引。",
            exp_en:"CONSORT, STROBE, TRIPOD+AI are EQUATOR reporting guidelines. HIPAA is a regulation, not a reporting guideline." },
          { type:"tf",
            stem:"是非題：DORA（San Francisco Declaration on Research Assessment）建議不以 Journal IF 評估個別研究者或單篇論文。",
            stem_en:"True/False: DORA recommends against using Journal IF to evaluate individual researchers or single papers.",
            ans:"T",
            exp:"DORA 2012 明文反對以 JIF 評鑑個別文章或研究者，NIH 自 2022 起也禁止在 biosketch 引用 IF。",
            exp_en:"DORA (2012) opposes using JIF to assess individual papers or researchers. NIH prohibits citing IF in biosketches since 2022." },
          { type:"single",
            stem:"在 response letter（回應審稿人）的標準結構為？",
            stem_en:"Standard structure of a response letter to reviewers:",
            A:"逐點：Reviewer comment → Our response → Changes in manuscript", A_en:"Point-by-point: Reviewer comment → Our response → Changes in manuscript",
            B:"只寫修改處", B_en:"Only list the changes",
            C:"只寫反駁", C_en:"Only rebut",
            D:"不需結構", D_en:"No structure needed",
            ans:"A",
            exp:"標準做法：引用審稿人原文、明確回應、註明稿件中修改位置與頁碼，禮貌且有依據地辯駁。",
            exp_en:"Standard: quote the reviewer verbatim, respond clearly, note manuscript changes with page numbers; rebut politely with evidence." },
          { type:"single",
            stem:"CRediT (Contributor Roles Taxonomy) 共有幾項角色分類？",
            stem_en:"How many roles does CRediT (Contributor Roles Taxonomy) define?",
            A:"4", A_en:"4",
            B:"7", B_en:"7",
            C:"14", C_en:"14",
            D:"20", D_en:"20",
            ans:"C",
            exp:"CRediT 列出 14 項貢獻角色（Conceptualization、Methodology、Software、Validation、Formal analysis、Investigation、Resources、Data curation、Writing - original draft、Writing - review & editing、Visualization、Supervision、Project administration、Funding acquisition）。",
            exp_en:"CRediT defines 14 roles: Conceptualization, Methodology, Software, Validation, Formal analysis, Investigation, Resources, Data curation, Writing - original draft, Writing - review & editing, Visualization, Supervision, Project administration, Funding acquisition." },
          { type:"single",
            stem:"撰寫 Discussion 段時，正確的「倒漏斗」結構為？",
            stem_en:"Correct 'inverted funnel' structure for the Discussion section:",
            A:"主要發現摘要 → 與文獻比較 → 限制 → 意義與未來方向", A_en:"Summary of findings → Comparison with literature → Limitations → Implications and future directions",
            B:"限制 → 限制 → 限制 → 限制", B_en:"Limitations → Limitations → Limitations → Limitations",
            C:"從廣泛背景到具體結果（漏斗式）", C_en:"From broad background to specific results (funnel)",
            D:"只列舉統計結果", D_en:"Only list statistics",
            ans:"A",
            exp:"Discussion 採「倒漏斗」結構：從具體發現開始，逐步擴大至文獻對照、機制、限制、最後到更廣的意義與未來方向。",
            exp_en:"Discussion uses an 'inverted funnel': start specific (your findings), expand to literature, mechanism, limitations, and finally broad implications." }
        ]

      }
    }
  }
};
